---
title: Reformas y Modernización de la Gestión Pública en Perú.
subtitle: Hacia una gestión eficiente y transparente en beneficio de la sociedad.
description: |
  Este ensayo explora la importancia de reformar y modernizar la gestión pública en Perú, abordando aspectos clave como la eficiencia, transparencia y mejora en la prestación de servicios.
categories:
  - Planeamiento y Presupuesto Público
tags:
  - Planeamiento-y-Presupuesto-Público
  - Gestión-Pública
  - Reformas-Estatales
  - Modernización-Administrativa
citation:
  author:
    - Edison Achalma
    - Felix Bermudo
    - Noe Borda
    - Kattya Castillo
    - Yuri Fernandez
  pdf-url: https://achalmaedison.netlify.app/docs/blog/posts/2021-10-01-reformas-modernizacion-gestion-publica-peru/index.pdf
date: "10/01/2021"
---

# ¿Qué hacer?

## ¿Reformar la gestión pública?

Para la reforma de la gestión pública se deben realizar acciones orientadas a incrementar los niveles de eficiencia y eficacia en la gestión pública a fin de que logre resultados en beneficio de los ciudadanos.

En este sentido se debe hacer especial mención en términos de tres hitos que expresan claramente una reforma de la gestión pública en Perú.

El primero guarda relación con el desarrollo de un Plan Estratégico de Modernización de la Gestión Pública, donde se debe definir una agenda de cambios en diversos ámbitos de la gestión pública, tales como mejora de los sistemas de planeación, la instalación de mejores mecanismos de control de gestión y la medición del quehacer de las instituciones públicas.

Segundo la instalación de un sistema de evaluación y control de gestión por parte de la Dirección de Presupuestos del Ministerio de Economía.

Y finalmente la creación del Sistema de Alta Dirección Pública que debe dotar a las instituciones de gobierno, a través de concursos públicos y transparentes, de directivos con probada capacidad de gestión y liderazgo para ejecutar de forma eficaz y eficiente las políticas públicas definidas por la autoridad.

## ¿Reformar el estado?

Para saber si reformar o qué reformas hacer del Estado debemos tener en cuenta algunas consideraciones iniciales. En ese sentido comenzamos a definir al Estado como el principal agente encargado del bienestar de la sociedad. Pero el Estado es una estructura dantesca que funciona bajo ciertas organizaciones, instituciones, normas jurídicas, reglas de juego, etc. En ese sentido el Gobierno, que es la representación del Estado busca brindar bienestar de la forma más eficiente y eficaz posible. Cuando los componentes del Estado no funcionan o si funciona, pero de forma ineficiente se requiere hacer una reforma del aparato estatal. Una reforma de estado tiene implicancia en el sector económico, político, social, etc.

En el Perú existe desde inicios del siglo XXI un aparato público muy endeble y se agravó producto de la pandemia del COVID-19 que trajo como consecuencia un incremento en la brecha social. Además de incrementarse la pobreza monetaria.

### Reforma política

Modificar la forma en que los gobiernos regionales y locales contratan a los gestores públicos. Que los gobiernos no contraten por afinidad; sino que los contratos lo realicen la Autoridad Nacional del Servicio Civil (SERVIR)

### Reforma económica

Las empresas nacionales y extranjeras deben competir en igualdad de condiciones.

### Reforma de salud

La digitalización de la atención médica. Implica que los doctores de distintas especialidades puedan atender a las personas de los lugares más alejados mediante plataformas digitales.

### Reforma agraria

Incentivar la producción intensiva para la exportación de bienes que se producen en territorios peruano

### Reforma tributaria

Que se incluya a los personajes influyentes (actores, gamers, cantantes, faranduleros) que brindan publicidad mediante sus redes sociales al pago de la renta de cuarta categoría.

Para realizar estas reformas es necesario que el gobierno tenga la capacidad de articular al sector público, privado y las universidades. Sin estas articulaciones las reformas del Estado serían esfuerzos perdidos.

## ¿Modernizar la gestión pública?

Se debe promover e intensificar en el país, una imagen positiva de la gestión pública, que debe estar al servicio de la sociedad peruana, dentro de un contexto de excelencia y no ser considerado como un sistema burocrático, sobredimensionado y conflicto social. La elaboración de los planes de desarrollo nacional a corto, mediano y largo plazo permitirán que el sector empresarial privado plantee sus planes tácticos y estratégicos, no sólo basado en la investigación de mercados y en la rentabilidad empresarial, sino también en el interés nacional.

La tarea inmediata es generar una cultura organizacional propia para la gestión pública, basada en la ética, transparencia y eficiencia en su accionar y en la prestación de sus servicios, constituyéndose en un paradigma de desarrollo nacional.

A diferencia de una empresa privada, la cual tiene como incentivo la maximización de su rentabilidad; las entidades públicas no cuentan con un estímulo natural para mejorar su funcionamiento. En consecuencia, las personas no pueden “optar por cambiar” a la entidad pública con la cual realiza un trámite u obtiene un servicio, como sí lo puede hacer con un proveedor privado en caso éste no satisfaga sus expectativas y necesidades. Por ello, a través de la modernización de la gestión pública se busca generar incentivos para que las entidades del Estado mejoren constantemente su funcionamiento e intervenciones (bienes, servicios y regulaciones) de forma eficiente, orientada a resultados y teniendo como prioridad a las personas.

La razón de ser de toda entidad y servidor público es brindar una mejor calidad de bienes, servicios y regulaciones a las personas. Se debe comprender que no se realiza “un favor” al ciudadano, sino es parte del cumplimiento de su trabajo.

Para ello, en el año 2019, la SGP emitió los Principios de Actuación para la Modernización de la Gestión Pública, los cuales tienen como objetivo orientar a las entidades hacia una correcta conceptualización de lo que es la modernización y hacia una gestión basada en la creación de valor público. Para ello, se plantean un conjunto de principios de actuación que todos los servidores civiles se comprometen a cumplir con el fin de acercarse y recuperar la confianza de las personas. Estos son:

- Diseñar e implementar políticas públicas cuyos resultados generen valor.
- Medir los resultados de las intervenciones.
- Pensar de manera sistémica los problemas.
- Responder mejor a las personas.
- Contar con bienes y servicios de calidad.
- Emitir regulaciones de calidad.
- Mejorar la productividad de las entidades públicas.
- Diseñar estructuras organizacionales interconectadas, ágiles y adaptables.

Con dichos lineamientos se busca que los servidores públicos comprendan a cabalidad su rol en la satisfacción de las necesidades de las personas y de la sociedad.

A pesar de dicha implementación y de todas las medidas tomadas en aras de lograr una modernización en la gestión pública brindada, no se han observado cambios significativos o los que se efectuaron pasaron desapercibidos, por lo tanto, se debe complementar a las medidas, un cambio absoluto en el control del cumplimiento de estas, ya que por mucho que se quiera cambiar, si es que no se hacen efectivas, al final solo se quedan en propuestas y los problemas continúan.

Por ello, los puntos que se debe considerar para una modernización más efectiva en la gestión pública son:

- Incorporar en la gestión pública a los mejores trabajadores; con la finalidad
- Capacitación permanente a los trabajadores
- Simplificación administrativa, a fin de generar resultados positivos en la mejora de los procedimientos y servicios orientados a los ciudadanos y empresas.
- Implementación y uso intensivo de las TIC como soporte a los procesos de planificación, producción y gestión de las entidades públicas permitiendo a su vez consolidar propuestas de gobierno abierto.

## ¿Modernizar el estado?

Dado que muchos bienes y servicios están bajo la asignación, supervisión, regulación y administración del estado, buscamos que se nos brinden estos de manera más eficiente, eficaz y de manera equitativa, una manera óptima; pues ¿necesitamos modernizarnos y/o adaptarnos a nuevas políticas públicas? O qué solución le damos, ante esto muchos nos hacemos esta pregunta ¿Cómo modernizamos el estado?

Modernizar el estado implica muchos aspectos de mejora y superación continua de los retos y objetivos del aparato estatal, claro basta redundar que se deben incluir la misión y visión de este, teniendo estos la característica de adaptabilidad al contexto de gobernabilidad democrática y relaciones emergentes entre el estado y los demás agentes económicos, lo cual implica adecuar la administración pública y hasta la gestión pública de acuerdo a los planes y políticas de desarrollo y crecimiento económico nacional, mediante reformas en el aparato estatal que faciliten el adecuada funcionamiento eficaz de este.

Tras hacer un análisis a nuestro aparato estatal determinamos retos para poder modernizarlo tales como establecer objetivos claros con orden de prioridad que muestren resultados al corto y largo plazo, seguir con la ley de descentralización de poderes, una simplificación administrativa con menos trabas en procesos burocráticos, el profesionalismo de la función pública multiplicando la capacidad de servicio del estado con una adecuada articulación integral de políticas y con transparencia de estas como su respectiva eficiencia, generalizando modernización de la gestión pública.

En la actualidad, el estado peruano podrá modernizarse siempre y cuando cumpla con los retos establecidos en sus planes de desarrollo nacional, llevará en buen camino la modernización de este con el adecuado uso de las reformas y objetivos trasados en los planes y políticas de desarrollo nacional ya establecidos en cada gobierno.

## ¿Reformar y modernizar la gestión pública?

El proceso de modernización y reforma del estado implica cambios trascendentales en toda la estructura y organización del aparato estatal. Involucrar a todos los actores constituye un verdadero desafío. La capacitación del personal y la adecuada publicidad de la estrategia y los objetivos estratégicos resultan trascendentales para lograr el compromiso de todos los miembros. El proceso de cambio es un camino complejo, que encuentra muchos escollos a su paso, en especial la resistencia de los propios dependientes. La cultura organizacional, los estilos de liderazgo y la estructura constituyen algunos de los ejemplos de las potenciales dificultades en el avance.

En este sentido tenemos las principales acciones para reformar y modernizar la gestión pública:

- Mejorar la calidad de prestación de bienes y servicios por parte del estado para cerrar brechas en esta acción.
- Se debe mejorar una convergencia de las actividades y los puntos de vista de la sociedad civil y las fuerzas políticas hacia el diseño de una visión compartida y los planes a nivel mundial estratégico
- Una descentralización que busca el fortalecimiento de los gobiernos locales y regionales como un mecanismo para y lograr la efectiva descentralización, este proceso debe ser de forma gradual.
- Se necesita mayor eficacia y eficiencia en el logro de los objetivos y en uso de los recursos por parte del estado. Esta es una actividad fundamental ya que primero se debe fijar correctamente los objetivos y utilizarse los recursos que tiene el estado. para lograr este uso eficiente de los recursos del estado, se debe eliminar la duplicidad y la superposición de funciones, competencias y atribuciones por parte de los diversos organismos que tiene el estado.
- Institucionalizar la evaluación de la gestión por resultados para medir las instituciones en base a los resultados ya que por ahora no hay una sanción especifica por haber tenido malos resultados y esto implica también que las capacidades del estado tienen que verse fortalecidas.

Esta tarea constituye un verdadero desafío que trasciende el color político de turno, persiguiendo como único fin el bienestar de toda la comunidad. Asimismo, implica la capacitación de los recursos humanos y el logro de la cohesión de objetivos organizacionales e individuales, brindando transparencia en la gestión y combatiendo la corrupción.
