---
title: Naturaleza Humana y su impacto político, sesgos científicos. Más allá de los Límites Impuestos
subtitle: Explorando las implicaciones políticas de nuestras concepciones sobre la naturaleza humana.
description: |
  Descubre cómo nuestras visiones sobre la naturaleza humana tienen consecuencias políticas, cómo los sesgos científicos pueden distorsionar la verdad y cómo podemos encontrar la libertad más allá de los límites impuestos. Explora los temas de género, igualdad y toma el control de tus propias creencias para una vida más consciente y libre.
categories:
  - Filosofía
tags:
  - Filosofía
  - NaturalezaHumana
  - Política
  - SesgosCientíficos
  - LibertadIndividual
  - IgualdadDeGénero.
citation:
  pdf-url: https://achalmaedison.netlify.app/docs/blog/posts/2023-06-09-naturaleza-humana/index.pdf
date: "06/09/2023"
---

# Introducción

## ¿El ser humano es inherentemente bueno o malo?

Rousseau sostenía que los seres humanos somos buenos por naturaleza,^[La afirmación "Rousseau sostenía que los seres humanos somos buenos por naturaleza" se basa en las ideas del filósofo Jean-Jacques Rousseau, específicamente en su obra "Discurso sobre el origen y los fundamentos de la desigualdad entre los hombres" (1755). En este libro, Rousseau argumenta que el hombre en su estado natural es esencialmente bueno, pero que la sociedad y la civilización corrompen su bondad innata.] mientras que Thomas Hobbes afirmaba que somos malos, tan malos que utilizaba la famosa frase _'el hombre es el lobo del hombre',_ sugiriendo que representamos un peligro para nosotros mismos.^[La afirmación sobre Thomas Hobbes y su famosa frase "el hombre es el lobo del hombre" se basa en las ideas presentadas en su obra principal, "Leviatán" (1651). En este libro, Hobbes argumenta que los seres humanos tienen una naturaleza egoísta y competitiva, y que sin un gobierno fuerte que imponga la ley y el orden, la sociedad se sumiría en el caos y la violencia.] Por otro lado, **Marx argumentaba que no existe una naturaleza humana determinada**, sino que somos producto de un conjunto de circunstancias y condiciones que nos moldean y modifican nuestra personalidad y comportamiento.^[La afirmación sobre la visión de Marx acerca de la naturaleza humana se encuentra en varias de sus obras, pero una de las más relevantes es "El Manifiesto Comunista" (1848). En este texto, Marx y Engels argumentan que la naturaleza humana no es fija ni determinada, sino que está moldeada por las relaciones sociales y económicas en un determinado sistema.]


Entonces profundizaremos en la importancia de elegir conscientemente nuestra definición de naturaleza humana y entender las implicaciones de nuestras creencias. Dependiendo de la idea de naturaleza humana que adoptemos, aceptaremos un conjunto de creencias que pueden permitir o limitar ciertas formas de ser, vivir y existir en el mundo.

# Definiciones de naturaleza humana

**¿Qué es la naturaleza humana?**. Existen múltiples respuestas populares a esta pregunta, y, por supuesto, el contenido de la definición varía según nuestras creencias y nuestra cultura. 

## Respuestas metafísicas y antimetafísicas

Aquellos que creen en la existencia de una naturaleza humana la justifican con argumentos no empíricos, es decir, con cosas que no pueden ser comprobadas en la realidad. Por ejemplo, los argumentos de Rousseau y Hobbes son de naturaleza metafísica, ya que no pueden ser respaldados por estadísticas o estudios biológicos. Por lo tanto, si queremos creer en la existencia de una naturaleza humana, ya sea buena o mala, debemos conformarnos con elegir el argumento **metafísico** más convincente, aunque no podamos comprobarlo en la realidad.

Existen otras formas de responder a la pregunta sobre la naturaleza humana, como la versión **antimetafísica**, que se asemeja más a la respuesta que nos da Marx. En este caso, vamos a explorar la respuesta que ofrece David Hume, quien, precisamente para oponerse a los argumentos metafísicos sobre la naturaleza humana, decidió describir nuestro aparato cognitivo y emocional. Observó al ser humano, recopiló datos de la realidad y dedujo conclusiones lógicas. A partir de esta descripción de cómo pensamos y sentimos, Hume define la naturaleza humana como ese conjunto de cualidades, descripciones y condiciones. Esto implica que nuestras capacidades intelectuales y afectivas son las que determinan nuestra naturaleza humana, y a su vez, las experiencias a las que estamos expuestos modifican estas capacidades tanto intelectuales como afectivas.^[La visión de David Hume sobre la naturaleza humana se sustenta en su obra principal, el "Tratado de la naturaleza humana" (1739-1740). En este tratado, Hume lleva a cabo un análisis empírico de la mente humana, examinando detalladamente los procesos de pensamiento, sentimiento y percepción que caracterizan nuestra experiencia del mundo. A partir de esta rigurosa investigación, Hume concluye que la naturaleza humana se comprende como un conjunto de cualidades, descripciones y condiciones, las cuales son moldeadas por nuestras capacidades intelectuales y emocionales, así como por las experiencias a las que nos vemos expuestos.]

## La perspectiva de David Hume y Karl Marx

Las respuestas de Marx y Hume son anti-metafísicas, ya que se basan en hechos que podemos más o menos comprobar en la realidad, en hechos humanos o sociales. Por otro lado, las respuestas de Rousseau y Hobbes son hipotéticas, ya que se basan en reflexiones e ideas hipotéticas.

Hobbes parte de la hipotética idea de un estado de naturaleza que se asemeja a una guerra en la que todos peleamos contra todos. Por otro lado, Rousseau parte de la hipotética idea del buen salvaje, imaginando a los primeros pobladores como buenos salvajes. Según Rousseau, es la sociedad la que nos corrompe y provoca que seamos menos buenas personas, pero esta corrupción es producto de la sociedad, no de nuestra naturaleza. Estos argumentos metafísicos se basan en cosas que no podemos comprobar en la realidad.

En contraste, las respuestas de Marx y Hume podríamos llamarlas más realistas, aunque el término correcto sería anti-metafísicas. Estas respuestas intentan basarse en hechos de nuestra realidad. En el caso de Hume, nos quedamos con la idea de que los seres humanos son el resultado de nuestras capacidades intelectuales y afectivas, lo que determina nuestra naturaleza. 

## La visión de Sigmund Freud

Sigmund Freud comparte esta idea con David Hume y Karl Marx, aunque con algunas variantes. Freud nos dice que todos somos víctimas de la naturaleza humana y que somos el resultado de nuestros traumas y deseos reprimidos. Según Freud, somos agentes pasivos en nuestras vidas, donde nuestras experiencias determinan absolutamente todo lo que somos. Desde este punto de vista, no tenemos mucha participación en la construcción de nuestra identidad, lo cual tampoco es una opción muy favorable, ya que no podemos hacernos cargo de nosotros mismos.^[La perspectiva de Sigmund Freud sobre la naturaleza humana se encuentra en su obra fundamental "La interpretación de los sueños" (1899). En este libro, Freud explora los procesos inconscientes y los mecanismos psicológicos que influyen en nuestra vida mental y emocional. Según Freud, nuestra naturaleza humana está determinada por los traumas y los deseos reprimidos que existen en nuestro inconsciente. Desde esta perspectiva, se considera que somos víctimas de nuestra propia naturaleza, y nuestras experiencias juegan un papel fundamental en la configuración de nuestra identidad. Freud sostiene que, en gran medida, somos agentes pasivos en la determinación de nuestras vidas y que carecemos de control total sobre nosotros mismos.]

> Lo importante de este tipo de pensamiento anti-metafísico es que nos permite definir la naturaleza humana sin necesidad de determinar ninguna esencia, lo cual es positivo.

# Implicaciones de las creencias sobre la naturaleza humana:

## Límites y convenciones de las esencias humanas

Observemos que cuando Rousseau y Hobbes determinaron la naturaleza humana como buena o mala, estaban estableciendo una esencia. Si creemos en Hobbes, afirmamos que somos esencialmente malos y estamos inclinados naturalmente a hacer daño a otros seres vivos. Por otro lado, si creemos en Rousseau, afirmamos que nuestra naturaleza es esencialmente buena y, por lo tanto, nos inclinamos a realizar actos buenos. Si reflexionamos sobre estas afirmaciones, nos damos cuenta de que al determinar una esencia, estamos definiendo cómo debe ser una cosa o una persona, imponiendo límites y delimitando la capacidad de acción. Es importante recordar que todo límite es una convención y no debemos olvidarlo.

## Justificación de acciones y responsabilidad ética

Por ejemplo, si considero que la naturaleza humana o la naturaleza de los seres humanos es mala, juzgaré mis actos malos como una inclinación natural en mí. Por lo tanto, podré justificarlos con menos responsabilidad ética, lo que limitará mi capacidad para evitar las malas acciones. Me veré obligado a realizarlas por naturaleza. Este escenario es desfavorable para aquellos de nosotros que creemos en nuestra capacidad para limitar efectivamente nuestros impulsos y reacciones ante nuestras emociones, sensaciones y sentimientos.

Por tanto, dependiendo de la definición de la naturaleza humana que decidamos creer, delimitamos nuestras posibilidades de ser y actuar en el mundo. 

> Recordemos que la respuesta metafísica sostiene que el ser humano tiene una esencia buena o mala, mientras que la respuesta anti-metafísica afirma que no tenemos una esencia, sino que somos el resultado de todo lo que nos sucede en la vida.

## Importancia de elegir una definición que aumente nuestras capacidades.

Personalmente, creo que debemos elegir el concepto de naturaleza humana que nos brinde mayor potencia, es decir, que incremente nuestras capacidades de ser y actuar en lugar de limitarlas. Por lo tanto, es crucial preguntarnos qué idea estoy aceptando como mi naturaleza humana, ya que estas ideas que formulamos como "naturales" en nosotros o en nuestra especie son las que delimitan nuestras posibilidades de ser y actuar.

## Influencia en la vida cotidiana y las relaciones sociales

Por ejemplo, si considero que la naturaleza humana implica diferencias de género justificadas por la división de sexos, como la creencia de que los hombres son menos sensibles que las mujeres y que las mujeres son menos racionales que los hombres, delimito mi potencialidad de ser. Dependiendo del sexo con el que nazca, si naciera mujer y considerara verdadera la afirmación anterior, me sentiría y actuaría como menos racional que todos los hombres. Tomaría mis decisiones de vida basándome en mis pasiones y emociones, sin tener claridad en mis razones, porque mi naturaleza sería ser sensible y no racional. Por otro lado, si naciera hombre y considerara que por naturaleza los hombres no somos sensibles, sino racionales, viviría toda mi vida sin prestar atención a mis emociones, reprimiendo mis sentimientos para demostrar mi supuesta superioridad racional y ser congruente con mi propia idea de mi naturaleza.

En cualquier caso, si justifico mi naturaleza y la de los demás a partir de estas creencias, mi vida está limitada y restringida por ellas. Ninguno de los dos escenarios es realmente deseable: ser una mujer irracional o un hombre insensible. Ambos privan a cada género de una parte muy importante de la vida. 

## Integración de pensamiento y sentimiento

Sabemos que todos los seres humanos tenemos el potencial de desarrollar y mejorar tanto nuestra racionalidad como nuestros sentimientos, y no tenemos por qué elegir uno u otro. De hecho, podríamos afirmar que esta separación entre sentimientos y pensamientos no es tan clara como nos gusta pensar. Los sentimientos generan pensamientos y viceversa. Existe un término muy hermoso, acuñado por el sociólogo Fals Borda, que es "sentipensar". Significa precisamente estas acciones, ideas y emociones que se entrelazan entre pensamientos y sentimientos. Esta idea del sentir pensante se adopta cuando Fals Borda entrevista a unos pescadores colombianos y les pregunta algo como: "¿Cuándo deciden salir a pescar?". La respuesta de ellos es: "Los sentipensamos, sentimos y pensamos al mismo tiempo, y cuando estamos de acuerdo en las emociones y en los pensamientos, ahí vamos a pescar".

Es interesante comenzar a integrar este tipo de términos, como el sentipensar, en nuestra vida cotidiana cuando no tenemos tan clara esta división entre el pensamiento y los sentimientos. Esta visión es muy cuestionable y parece ser incorrecta, aunque haya sido así en el desarrollo de la humanidad.

## Cuestionamiento de las afirmaciones sobre la naturaleza humana

Ahora, imagina que considero que la naturaleza humana implica que las personas son inherentemente egoístas y solo se preocupan por su propio beneficio. Si adopto esta creencia como verdadera, entonces justificaré mis acciones egoístas como algo natural y esperado. Esto limitará mi capacidad para actuar de manera altruista o preocuparme por el bienestar de los demás, ya que me sentiré obligado a actuar de acuerdo con mi supuesta naturaleza egoísta. En consecuencia, estaré coartado por esta idea y no podré experimentar el pleno potencial de ser una persona generosa y empática.

Sigamos con los ejemplos. Si considero, por ejemplo, que todos los seres humanos somos malos y pecadores por naturaleza, estoy asumiendo que las personas toman malas decisiones de manera inherente, sin importar cuáles sean los pecados en cuestión. Esto implica que todos estamos alejados del bien debido a nuestra condición de pecadores, según la teoría, y que esto es parte de nuestra naturaleza. Este tipo de argumentación nos lleva a justificar nuestras malas acciones y las de los demás como algo natural e inevitable, lo que nos exime en gran medida de la responsabilidad ética de nuestros actos. Comienza un juego de autojustificación a nivel personal.

Estos argumentos sobre la naturaleza humana pueden afectarnos en múltiples formas. Por un lado, pueden llevarnos a llevar una vida construida en torno a evitar el pecado a toda costa, generando un comportamiento represivo hacia nosotros mismos y hacia los demás pecadores. Esto puede conducir a altos niveles de violencia, ya que podemos justificar actos violentos como inevitables debido a nuestra supuesta naturaleza violenta. Por ejemplo, **podemos llegar a justificar el maltrato a niños o animales con el fin de educarlos, entre otras cosas aún peores.** Esta justificación se basa en la supuesta presencia de violencia en nuestra naturaleza.

> Es importante señalar que el término **"violencia"** es complejo y merece una reflexión más profunda. No toda violencia es necesariamente negativa, y su papel en nuestra vida cotidiana es un tema que merece ser explorado en futuras discusiones.

A nivel social, este tipo de justificaciones basadas en la idea de que la naturaleza humana es mala pueden llevarnos a justificar altos niveles de represión social en aras de mantener el orden. Según esta perspectiva, el Estado tendría la obligación de protegernos de todas las amenazas, incluso si la amenaza somos nosotros mismos. Así, se pueden tomar decisiones que limiten nuestras libertades individuales en pos del supuesto bienestar de los ciudadanos. Thomas Hobbes, por ejemplo, utiliza la noción de que los seres humanos son malvados y ambiciosos para justificar un sistema político conocido como monarquía absoluta, en el cual se limita, mediante la fuerza, la naturaleza malvada de las personas. Es importante observar cómo se utilizan estas argumentaciones sobre la naturaleza humana en el ámbito político, ya que pueden moldear la organización y el orden social en el que vivimos. Dependiendo de la perspectiva que aceptemos, se puede favorecer un sistema con mayor represión o uno que garantice mayores libertades.

Es crucial cuestionar estas afirmaciones sobre la naturaleza humana, como la de Thomas Hobbes, y plantearnos si realmente somos capaces de modificar nuestra supuesta naturaleza malvada, o si somos totalmente incapaces de hacerlo. También debemos cuestionar si esta es verdaderamente nuestra naturaleza, ya que hemos visto que existen diversas respuestas posibles que difieren de las afirmaciones de Hobbes.

## Implicaciones políticas y el significado de lo político en la filosofía

Es importante recordar que al definir la naturaleza humana, también nos estamos definiendo a nosotros mismos. Elegir una perspectiva sobre la naturaleza humana implica tomar una posición política. No existe ninguna definición de naturaleza humana que no tenga implicaciones políticas. Sería interesante dedicar un artículo completo a explorar el significado de lo político en la filosofía, ya que va mucho más allá de la política que conocemos.

Debemos comprender que lo político es mucho más profundo que la simple noción de participar en elecciones, tener partidos políticos o ver políticos haciendo promesas en la televisión. En términos filosóficos, lo político implica que cuando una libertad entra en contacto con otra, se crea una situación política. En ese momento, debemos mediar, negociar y aprender a establecer límites. Lo político atraviesa todos los ámbitos de nuestra vida. No debemos limitarlo a la idea tradicional de la política pública o social. Es un concepto mucho más amplio y esencial en nuestras interacciones cotidianas.

Por ahora, dejemos aquí esta reflexión sobre lo político. En futuros publicaciones, profundizaremos más en este tema y exploraremos su importancia en nuestras vidas.

**¿Por qué elegir nuestra concepción de la naturaleza humana se convierte en un posicionamiento político?** La elección de nuestra naturaleza humana implica establecer límites a nuestra propia naturaleza, y es en este punto donde surge la noción de lo político. Por ejemplo, al seleccionar una definición de naturaleza humana, se generan sesgos interpretativos en ámbitos que se consideran objetivos, como la ciencia. Nuestra concepción de la naturaleza humana puede influir en la interpretación de los resultados de investigaciones científicas.

## Implicaciones científicas

Un ejemplo de sesgo interpretativo se puede encontrar en el trabajo del neurocientífico Broca, descrito en su libro "El cerebro de Broca". En su estudio, Broca comparó 292 cerebros masculinos con 140 cerebros femeninos y encontró que el cerebro de las mujeres pesaba, en promedio, 181 gramos menos que el de los hombres. Sin embargo, Broca interpretó esta diferencia en masa cerebral como evidencia de la supuesta inferioridad de las mujeres, sin tener en cuenta que la variación podría explicarse fácilmente por diferencias de estatura y tamaño corporal. Broca no intentó contextualizar estos datos ni cuestionar su propia conclusión, sino que afirmó que esto confirmaba las diferencias de género, llegando incluso a declarar que "las mujeres son menos inteligentes que los hombres"

Este ejemplo ilustra cómo la percepción individual de la naturaleza humana puede influir en nuestros actos, conclusiones y experimentos en el mundo. La ciencia tampoco está exenta de esta influencia interpretativa. Aunque posee un grado de objetividad, está sujeta a métodos y formas interpretativas que permiten la apertura a la subjetividad. Por lo tanto, es importante reconocer que incluso la ciencia interpreta el mundo a partir de nuestras concepciones sobre la naturaleza humana.

El caso de Broca demuestra cómo nuestra noción de la naturaleza humana moldea y perfila nuestras acciones y conclusiones. En su caso, la concepción de la naturaleza humana implicaba que los hombres eran más inteligentes que las mujeres, y utilizó los datos de su experimento para afirmar y reafirmar esta creencia. No se le ocurrió cuestionar la veracidad de la afirmación de que las mujeres son menos inteligentes que los hombres, ya que esta idea le parecía natural y encajaba con su concepción de la naturaleza. No consideró que la diferencia en el tamaño cerebral pudiera estar relacionada con la complexión física de las personas en lugar de ser determinada únicamente por el género.

> Esto nos muestra que incluso la ciencia, que a menudo se considera el lenguaje más objetivo, interpreta el mundo a partir de nuestras concepciones de la naturaleza humana. Es esencial reconocer que nuestras creencias sobre la naturaleza humana pueden influir en nuestra comprensión de los resultados científicos y en nuestras acciones en el mundo.

En la actualidad, podemos hablar del neurosexismo, un tipo de sesgo ideológico que incluso existe dentro de la neurología, la ciencia y la medicina, así como en muchos otros ámbitos. Gracias a este tipo de análisis, podemos afirmar con total certeza que ninguno de los dos sexos es más inteligente o sensible que el otro. Si están interesados en profundizar en este tema del neurosexismo, les recomiendo un libro muy importante llamado "El género del cerebro" de Gina Ripo. Es un análisis profundo realizado por una destacada neuróloga que observa cómo gran parte de la historia de la neurociencia ha estado influenciada por cuestiones de género.

# Conclusión

A partir de los ejemplos que acabamos de mencionar, podemos observar que la definición de la naturaleza humana que adoptamos de manera personal, así como la definición que adopta nuestra sociedad y cultura, establecen los límites de lo que podemos ser y lo que nos permitimos ser. Nuestras creencias personales y las demandas y expectativas sociales influyen en nuestras acciones y en la forma en que nos desenvolvemos en la vida. Detrás de todos estos límites impuestos por la sociedad y por nosotros mismos se encuentra la concepción de la naturaleza humana.

Por lo tanto, es de vital importancia revisar nuestras creencias, ya que moldean nuestra vida y la hacen posible. Es saludable asumir la responsabilidad de nuestras propias creencias, es decir, **comprender por qué creemos lo que creemos y cómo justificamos esas creencias.** Esto nos permitirá tomar un mayor control sobre nuestra propia vida y actuar de manera más consciente.
