---
title: "Hello, I'm Edison Achalma."
subtitle: "Economista"
format:
  html:
    include-in-header:
    - '../download/_download.html'
page-layout: full
toc: false
anchor-sections: false
editor: source
resources:
  - images/hero_animation.mp4
---

::: hero-banner
::: content-block
::: hero-text
-   LinkedIn: [linkedin.com/in/achalmaedison](https://linkedin.com/in/achalmaedison)
-   GitHub: [github.com/achalmed](https://github.com/achalmed)
-   Sitio web: [achalmaedison.netlify.app](https://achalmaedison.netlify.app)
-   Teléfono: +51 934 179 301
-   Correo electrónico: [achalmed.18\@gmail.com](mailto:achalmed.18@gmail.com)

Ubicación: Asoc Micaela Bastidas Mzna D1 - N° 06, Jesús Nazareno, Ayacucho - Perú

Como estudiante de Economía en mi último ciclo en la Universidad Nacional de San Cristóbal de Huamanga, estoy entusiasmado por la oportunidad de unirme a una entidad privada o pública que me permita aplicar mis conocimientos y habilidades mientras sigo desarrollándome profesionalmente. Con una formación especializada, estoy seguro de que puedo aportar valor a una entidad que comparta mis valores y expectativas.

Soy una persona altamente organizada y motivada, capaz de adaptarme a cualquier entorno y ofrecer siempre lo mejor de mí en cualquier proyecto. Me apasiona trabajar en equipo y fomentar valores como el compañerismo en el lugar de trabajo. Estoy ansioso por contribuir a una organización que valore el crecimiento profesional y la colaboración.
:::

::: hero-animation
<video autoplay muted playsinline loop>

<source src="images/hero_animation.mp4" type="video/mp4"/>

</video>
:::
:::
:::

# Experiencias {.experiencias}

::: experiencia
::: experiencia_date
Abril 2022 - Julio 2022
:::

::: experiencia_titulo
Docente, UNIVERSIDAD AUTÓNOMA DE HUANTA, Huanta
:::

::: experiencia_descripcion
Enseñé el curso de Gestión de Proyectos a estudiantes de pregrado en la UNH, lo que me permitió desarrollar habilidades de enseñanza y comunicación efectiva.
:::
:::

::: experiencia
::: experiencia_date
Agosto 2021 - Abril 2022
:::

::: experiencia_titulo
Practicante, DIRECCIÓN DE INFORMACIÓN AGRARIA Y ESTUDIOS ECONÓMICOS, DRA-Ayacucho
:::

::: experiencia_descripcion
Contribuí en la formulación de estudios económicos y en la generación y procesamiento de información relevante para el sector agrario de la región. Adquirí habilidades en análisis de datos, investigación y trabajo en equipo en un entorno profesional.
:::
:::

::: experiencia
::: experiencia
Agosto 2021 - Julio 2020
:::

::: experiencia
Secretario, CENTRO DE ESTUDIANTES DE ECONOMÍA, Ayacucho
:::

::: experiencia
Como Secretario de Prensa del Centro de Estudiantes de Economía, fui responsable de la difusión de las actividades y eventos del centro, así como de mantener una comunicación fluida y efectiva con los estudiantes y demás miembros del centro. Desarrollé habilidades en comunicación, trabajo en equipo y organización.
:::
:::

::: experiencia
::: experiencia
Abril 2019 - Enero 2019
:::

::: experiencia
Secretario de archivos, MUNICIPALIDAD PROVINCIAL DE CANGALLO., Cangallo
:::

::: experiencia
Desempeñé el cargo de Secretario de Archivos en la Oficina de Archivos de la Municipalidad Provincial de Cangallo.
:::
:::

::: experiencia
::: experiencia
Diciembre 2018 - Enero 2018
:::

::: experiencia
Parlamentario Joven, CONGRESO DE LA REPÚBLICA, Ayacucho
:::

::: experiencia
Auspiciado por la Fundación Hanns Seidel y la Oficina de Participación Ciudadana del Congreso de la República del Perú, fortalecí mis capacidades de liderazgo y aprendí sobre el funcionamiento del Congreso de la República, sus comisiones de trabajo y la valoración del trabajo en un espacio de participación y fomento de valores democráticos.
:::
:::

# Formación académica {.educacion}

::: educacion
::: educacion_date
2017 - Hoy
:::

::: educacion_titulo
Universidad Nacional de San Cristóbal de Huamanga
:::

::: educacion_grado
Economía, Ayacucho
:::
:::

::: educacion
::: educacion_date
2020-Hoy
:::

::: {#educacion_titulo}
INSTITUTO CULTURAL PERUANO NORTEAMERICANO
:::

::: educacion_grado
Huamanga Nivel Básico B10
:::
:::

::: educacion
::: educacion_date
Diciembre 2013 - Marzo 2009
:::

::: educacion_titulo
I.E.P. "SIETE DE JUNIO"
:::

::: educacion_grado
C.P. Catalinayocc EBR (Educación Básica Regular)
:::
:::

# Conocimientos informáticos {.conocimiento_inf}

::: {#informatica .informatica}
Programación

-   Fundamentos de programación
-   Machine learning con R
-   MATLAB
-   Python
-   Visual Basic
:::

::: informatica
Microsoft Office

-   Word Intermedio
-   Excel Intermedio
:::

::: informatica
Software

-   EViews
-   LáTex
-   Stata
:::

# Idiomas {.idiomas}

::: idiomas
-   Español:
-   Quechua:
-   Inglés:
:::

# Habilidades destacadas {.habilidades}

::: {#habilidades .habilidades style="color: tomato"}
-   Liderazgo
-   Motivado
:::

# Logros {.logros}

::: {#logros .logros}
-   2022: Ubicado en el tercio superior de mi escuela profesional durante todo mi tiempo en la universidad, reconocimiento otorgado por la excelencia académica en mi carrera.
-   2022: Autor de varios publicaciones, entre los que se destacan el Boletín Estadístico de Palto Ayacucho, Encuesta Nacional de Intenciones de Siembra Campaña Agrícola 2022-2023 y Boletín Estadístico de Quinua Ayacucho, que han sido ampliamente reconocidos por su rigor y calidad.
-   2018: Fui seleccionado para participar en el Plenario Regional como Parlamentario Joven en 2018, organizado por la Oficina de Participación Ciudadana del Congreso de la República. Como uno de los pocos seleccionados de entre un gran número de participantes, tuve la oportunidad de representar a mi región y fortalecer mis habilidades de liderazgo y debate constructivo en un espacio importante para la promoción de valores democráticos.
-   2017: Becario de Beca Permanencia 2017, lo que me permitió seguir estudiando y desarrollando mis habilidades en mi carrera universitaria, logrando así una mayor preparación para enfrentar nuevos desafíos.
:::

# Proyectos {.proyecto}

::: proyecto
CHAT BOT

2021 - 2022

-   Repositorio: [github.com/achalmed/bot-whatsapp](https://chat.openai.com/c/github.com/achalmed/bot-whatsapp)
-   Descripción: Creación e implementación de un chatbot para la MDSJB-Ayacucho utilizando node.js y dialogflow.
-   Tecnologías utilizadas: Node.js, Dialogflow.
-   Herramientas utilizadas: Whatsapp.
:::

# Voluntaridos {.voluntariado}

::: voluntariado
**NATS de Movimiento de Adolescentes y Niños Trabajadores Hijos de Obreros Cristianos -- MANTHOC**

-   Año: 2016
:::

::: voluntariado
**Corresponsal de No Apto Para Adultos -- NAPA**

-   Año: 2014
-   Descripción: Colaboración en la creación del magazine televisivo diario de media hora de duración con información y reportajes de actualidad para niños y adolescentes de 13 a 17 años. NAPA es difundido por 40 canales de Red TV en todo el Perú, y en Lima a través de la señal de JN19 UHF y en el canal 57 de Cable Mágico.
:::

# Cursos y/o estudios complemetarios {.curso}

-   ::: curso
    -   2022 - Diplomado de especialización en ofimática profesional, Escuela Superior de Negocios y Asesoría Profesional, NR : 49823

    -   2022 - Diplomado de especialización en sistemas gubernamentales : SIAF, SIGA Y SEACE, Instituto Interamericano de Alta Asesoría Empresarial, NR : 0035470

    -   2022 - Curso de redacción de documentos académicos, Centro de Competencias del Agua - CCA-AA-PICS-001

    -   2021 - Foro regional de Alto Desarrollo Lima y Callao de CAENE, ID de la credencial : 21FLC05-079

    -   2020 - Finanzas básicas y planeamiento estratégico, de Grupo IDDEA, ID de la credencial : CERT EEA FBYPE SM CE2229

    -   2020 - Inversión Extranjera como Motor del Desarrollo para América Latina y el Caribe, de Banco Interamericano Del Desarrollo

    -   2019 - Corrupción, sistema financiero y distribución de las riquezas en el Perú, de Universidad Nacional San Luis Gonzaga de Ica

    -   2018 - IV ENCUENTRO DE LÍDERES EMPRESARIALES ELE18 de Confederación Nacional de Instituciones Empresariales Privadas (CONFIEP)

    -   2017 - Plataformas de marketing digital & social media business, Google for Education
    :::

# Referencias {.referencia}

::: referencia
Leny Palma - Encargada de Oficina de Participación Ciudadana del Congreso de la República 2018, CONGRESO DE LA REPÚBLICA

-   Email: [parlamentojoven\@congreso.gob.pe](mailto:parlamentojoven@congreso.gob.pe)
-   Teléfono: +687 987 654
:::

::: referencia
Mag. Econ. Efraín Castillo - Director de la Escuela de Economia, ECONOMÍA UNSCH

-   Email: [efrain.castillo\@unsch.edu.pe](mailto:efrain.castillo@unsch.edu.pe)
-   Teléfono: +51 966 935 394
:::

::: referencia
Mag. Ing. William Blas Torres Gutiérrez - Director de la Direccion de Información Agraria y Estudios Económicos, DIAEE

-   Email: [dia\@agroayacucho.gob.pe](mailto:dia@agroayacucho.gob.pe)
-   Teléfono: (66)312387
:::

# Publicaciones {.publicacion}

::: publicacion
-   Boletín Estadístico de Palto Ayacucho, Ayacucho (2022)

-   Encuesta Nacional de Intenciones de Siembra Campaña Agrícola 2022-2023, DRA Ayacucho (2022)

-   Boletín Estadístico de Quinua Ayacucho, Ayacucho (2022)
:::