---
title: Aprende a usar Google Assistant Comandos útiles y trucos
subtitle: Maximiza tu experiencia con el asistente virtual de Google
description: |
  Descubre los comandos más útiles y trucos para utilizar Google Assistant en tu vida diaria. Desde programar recordatorios hasta controlar dispositivos inteligentes en tu hogar, este blog te mostrará cómo aprovechar al máximo esta herramienta.
categories:
  - Tecnología
  - Productividad
  - Asistentes Virtuales
tags:
  - Google Assistant
  - Comandos de voz
  - Trucos de productividad
  - Automatización
author: Achalma Mendoza Elmer Edison
date: "05/23/2020"
date-modified: "today"
draft: false
---

Basic

Stop playing

- OK Google, stop. / stäp

Pause  

- OK Google, pause. / pôz
- OK Google, resume.  /  rəˈzo͞om

Control the volume

- OK Google, increase volume.  /ɪnˈkris/  /ˈvɑl·jum, ˈvɑl·jəm/
- OK Google, volume up.
- OK Google, decrease volume.
- OK Google, volume down.

Ask for help

- OK Google, help.

Examples of what you can ask

- OK Google, what can you do?

Ask to repeat the last phrase

- OK Google, repeat.

Change Google Assistant's voice

- OK Google, change your voice.

You can string two commands together  

- OK Google, what is time, and what's the weather?

Bluetooth

Pair a Bluetooth device

- OK Google, pair Bluetooth.

Connect to a Bluetooth device

- OK Google, connect.
- OK Google, connect to my phone.

Disconnecting from a Bluetooth device

- OK Google, disconnect.
- OK Google, disconnect from my phone.

Calendar

Hear information about agenda / Calendar

- OK Google, what's my calendar for today?
- OK Google, what's my agenda for Friday?
- OK Google, calendar for tomorrow.

Add a calendar event

- OK Google, add an event to my calendar.
- OK Google, add the meeting to my calendar for tomorrow at 5 p.m.

How many days until holiday

- OK Google, how many days until Christmas?
- OK Google, how many days until new year?

Calls and messages

Call a contact

- OK Google, call.
- OK Google, make a call.
- OK Google, call Eugene.
- OK Google, call Eugene on speaker.
- OK Google, find Eugene phone number.

SMS

- OK Google, SMS.
- OK Google, text Eugene.
- OK Google, text John <<Buy some milk>>.
- OK Google, message to John <Hello, John>.

Send a WhatsApp or Viber message

- OK Google, message Eugene via WhatsApp.
- OK Google, message Eugene via Viber.
- OK Google, message Eugene <Hello, Eugene>.
- OK Google, WhatsApp John.
- OK Google, Viber John.
- OK Google, voice message to Eugene.
- OK Google, voice message to Eugene via WhatsApp.

Calculator

Arithmetic

- OK Google, multiply 15 to 16.
- OK Google, what's 15 times 16?
- OK Google, what is 15% of 50?
- OK Google, what's the square root of 42?

Unit Converter

- OK Google, how many meters are in a mile?
- OK Google, 10 inches in meters.
- OK Google, how many grams are in a kilogram?
- OK Google, 5 liters in gallons.
- OK Google, how many pounds in a kilo?

Currency exchange rate

- OK Google, how many dollars is a euro?
- OK Google, 15 US dollars in Russian rubles.

Stock Exchange

- OK Google, What's the stock price of Apple?
- OK Google, how much the bitcoin costs?

Cooking

Named timer

- OK Google, set chicken timer to 10 minutes.
- OK Google, how much time is left for chicken?

Dish caloricity

- OK Google, how many calories are in a beefsteak?
- OK Google, how many calories are in a glass of Cola?

The nutritional value

- OK Google, how much sugar in Cola?
- OK Google, how much protein in chicken?
- OK Google, how much vitamin A in a carrot?

Dictionary

 Word meanings

- OK Google, What is the definition of the word <instant>?
- OK Google, What does the word <mammal> mean?
- OK Google, find the definition of <agila>.

Word spelling

- OK Google, How do you spell <ambassador>?

Easter Eggs

Getting to know Google Assistant

- OK Google, what are you?

- OK Google, what's your favorite color?

- OK Google, how are you?

- OK Google, do you have kids?

- OK Google, what's your quest ?

- OK Google, tell me about your childhood.

- OK Google, can you drive?

- OK Google, who made you?

- OK Google, where do you live?

- OK Google, what do you dream about?

- OK Google, do you have feelings?

Party tricks

- OK Google, I need the poem.

- OK Google, tell me a story.

- OK Google, roll a dice.

- OK Google, flip a coin.

- OK Google, tell me a joke.

- OK Google, sing a song.

- OK Google, beatbox.

- OK Google, tell me something I don't know.

- OK Google, sing a lullaby.

- OK Google, what am I thinking now?

- OK Google, surprise me.

Email

Send email

- OK Google, email.

- OK Google, send an email.

- OK Google, send an email to Eugene.

- OK Google, send email to Eugene <Buy some milk>>.

Geography  

Country facts

- OK Google, how many people live in Russia?

- OK Google, what's the capital of Austria?

- OK Google, Spain area.

Facts about oceans/seas/rivers/lakes

- OK Google, biggest ocean.

- OK Google, Depth of the Pacific Ocean

- OK Google, the saltiest ocean.

- OK Google, the longest river.

- OK Google, what's the longest river in Russia?

- OK Google, deepest lake.

- OK Google, the deepest lake in Canada.

Discover facts about nature

- OK Google, why is the sky blue?

- OK Google, where does the rain come from?

History

Historical events

- OK Google, what happened during enlightenment?

- OK Google, when did World War 2 begin?

- OK Google, Olympic Games in the USSR.

- OK Google, when was the Cold War?

Lists

Add item to the list

- OK Google, add bread to my shopping list.

- OK Google, add milk and potatoes to my shopping list.

Ask what's on list

- OK Google, what's on my shopping list?

- OK Google, my shopping list.

Music

Play music on Google Music

- OK Google, play some music on Google Play.

- OK Google, play jazz music on Google Play.

Play a Google Music playlist

- OK Google, play my Trance playlist on Google Play.

Play a song

- OK Google, play <Can't Stop> on Google Play Music.

- OK Google, plays <At The End> by <Linkin Park>.

Play an artist

- OK Google, play music by Taylor Swift.

- OK Google, play One Republic.

Play an album

- OK Google, play the last U2 album.

- OK Google, play Essential Classical on Google Play.

Control what's playing

- OK Google, next.

- OK Google, previous.

- OK Google, repeat this song.

Fast forward or rewind

- OK Google, ski forward 1 minute.

- OK Google, skin back 1 minute.

Play music based on genre /mood/activity

- OK Google, play some fun music.

- OK Google, play music for a workout.

- OK Google, play songs for sleeping.

Find the song by part of the lyrics

- OK Google, play the song that goes: <Head out on the highway>.

Ask what's playing

- OK Google, what song is this?

- OK Google, what song is playing?

- OK Google, what's this album?

Get information

- OK Google, who sings the song <Let It Go>?

- OK Google, who is in the band <Daft Punk>?

- OK Google, what year did Linkin Park release <Hybrid Theory>

Movies

Today in the cinema

- OK Google, what movies are playing tonight?

- OK Google, movie schedule.

Movies short summary

- OK Google, tell me about the movie "The Matrix".

- OK Google, «Blade Runner» duration

- OK Google, how many seasons in "Game of Thrones"?

Info about actors

- OK Google, who plays in "Blade Runner"?

- OK Google, what is Johnny Depp's latest movie?

- OK Google, how many Oscars has Tom Cruise won?

- OK Google, who plays Doctor Who?

News

Listen to the latest news

- OK Google, tell me the news.

- OK Google, news.  

Listen to the latest news about a specific news category

- OK Google, what's the latest in technology?

- OK Google, sports news.

Ask what's playing (news)

- OK Google, what's playing?

Summary of your day, including weather, traffic, and some news.

- OK Google, what's my Flash Briefing?

Navigation

Routes

- OK Google, the pathway to the nearest supermarket.

- OK Google, the route to Moscow.

Hear commute conditions

- OK Google, what's the traffic?

- OK Google, what's the traffic like?

Travel time to home or work

- OK Google, how long drive to work?

- OK Google, time to home.

Specify destination

- OK Google, how long will it take to drive to Red Square?

- OK Google, how long will it take to walk to Historical Museum?

Nearby places

- OK Google, where's the nearest swimming pool?

- OK Google, find me a fast food store.

- OK Google, where can I buy a coffee?

People

Facts about celebrities

- OK Google, who is James Watson?

- OK Google, tell me about Thomas Edison.

- OK Google, how tall is Barack Obama?

- OK Google, who invented the phone?

- OK Google, when was Donald Trump born?

- OK Google, who is the president of Croatia?

Physics & Chemistry  

Physical

- OK Google, gravity on Earth.

- OK Google, speed of light.

- OK Google, what is gravity?

- OK Google, Newton's first law.

Chemical

- OK Google, air composition.

- OK Google, petroleum composition.

- OK Google, the atomic number of oxygen.

- OK Google, uranium half-life.

Places

Near places

- OK Google, where's the nearest swimming pool?

- OK Google, find me a fast food shop.

- OK Google, where can I buy a coffee?

Radio

Listen to the radio station by <Radio Station Name> using the Tuneln Radio app

- OK Google, play Bloomberg Radio on Tunnel.

- OK Google, play BBC on Tunnel.

Listen to radio station by frequency

- OK Google, play 103.1 FM.

- OK Google, play 106.1 FM Boston.

Reminders

Create a time-based reminder

- OK Google, create a reminder.

- OK Google, a new reminder.

Create a time-based reminder for a specific action

- OK Google, remind me to visit Mom.

- OK Google, remind me to buy milk.

Create a time-based reminder at one go

- OK Google, remind me to call Grandma tomorrow at 9 p.m.

- OK Google, remind me to buy some coffee on Friday at 10p.m.

Check reminders

- OK Google, what's in my reminders?

- OK Google, what are my reminders for tomorrow?

- OK Google, my reminders for tomorrow.

- OK Google, check my reminders.

- OK Google, check all my reminders.  

Cancel reminders

- OK Google, delete the reminder.

- OK Google, remove the reminder.

- OK Google, cancel the reminder to buy milk.

- OK Google, delete all reminders.

Smart Home

Call on Android-phone

- OK Google, where is my phone?

Control the light

- OK Google, turn on lights.

- OK Google, turn off lights.

Controls the brightness of light

- OK Google, set the lights to 50%.

Control the smart plug

- OK Google, turn on my smart plug.

- OK Google, turn off my smart plug.

Control the thermostat

- OK Google, raise temp 2 degrees.

- OK Google, set the temperature to 72.

- OK Google, what's the temperature inside?

Sports

Sports news

- OK Google, what is my Sports Update?

Result of last match

- OK Google, what was the score for the Washington Capitals game?

- OK Google, last Chicago Bulls game?

- OK Google, did Washington Capitals win?

League position

- OK Google, how are the Lakers doing?

- OK Google, what are the Pittsburgh Penguins standings?

Next match time

- OK Google, when Washington Capitals playing next?

The club's roster

- OK Google, French national football team lineup.

- OK Google, who plays for Real Madrid?

- OK Google, Barcelona team lineup.

- OK Google, Washington Capitals roster.

Get player info

- OK Google, where does Messi play?

- OK Google,  what team does Cristiano Ronaldo play for?

- OK Google, Cristiano Ronaldo height.

- OK Google, Messi's age.

Timer & Alarm

Find out time / Date

- OK Google, what time is it?

- OK Google, what's the date?

Time zones

- OK Google, what time is it in Berlin?

- OK Google, time in New York?

- OK Google, the time difference between Moscow and Washington.

Set a timer

- OK Google, set a timer for 1 minute.

- OK Google, set timer 5 minutes for paste.

Set a timer with name

- OK Google, set timer  <Pizza> for 5 minutes.

- OK Google, set timer <Pasta> for 10 minutes.

Check timers

- OK Google, my timers.

- OK Google, how much time is left for pasta?

Cancel timers

- OK Google, cancel timers.

Set an alarm

- OK Google, set an alarm for 8 a.m.

- OK Google, set an alarm for weekdays at 7 a.m.

- OK Google, snooze.

- OK Google, snooze for 10 minutes.  

Check / Cancel alarms

- OK Google, what alarms are set?

- OK Google, cancel my alarms.  

Set a sleep timer

- OK Google, set a sleep timer for 30 minutes.

- OK Google, stop playing in 30 minutes.

Translations

Translate to Russian

- OK Google, how do we say <good night>> in Russian?

- OK Google, translates <Excusez-Moi> to Russian.

Translate to French

- OK Google, how do we say <excuse me> in French?

Translate to German

- OK Google, translate <Good evening> to German.

Translate to Spanish

- OK Google, how do we say <Guten Tag> in English?

Travel

Flights

- OK Google, how much is a round-trip flight to New York?

- OK Google, how much is a one-way flight to New York cost?

- OK Google, how much are flights to St. Petersburg in weeks?

- OK Google, prices for an airline ticket to St. Petersburg.

- OK Google, find me flights to Paris.

- OK Google, what is the schedules for flights to New York?

- OK Google, find flights with United Airlines?

- OK Google, the state of United Airlines 515.

- OK Google, when does Delta Flight 315 arrive?

- OK Google, when does United Airlines 515 leave?

Find restaurant to try  

- OK Google, what hotels are nearby?

- OK Google, hotels in Moscow.  

Discover place to visit

- OK Google, attractions in Saint Petersburg?

- OK Google, things to do in St. Petersburg?

TV

Control TV

- OK Google, turn on TV.

- OK Google, volume up.

- OK Google, volume down.

- OK Google, turn off my TV.

Play music

- OK Google, play rock music on my TV.

- OK Google, play Eminem on my TV.

Play radio

- OK Google, play NBC on Tunnel on my TV.

- OK Google, play BBC on Tunnel on my TV.

Play recommended video on YouTube

- OK Google, play YouTube.

- OK Google, open YouTube.

- OK Google, next.

- OK Google, turn on subtitles

Find the video on YouTube  

- OK Google, play funny cat videos

- OK Google, play the latest from Euronews.

- OK Google, play yoga videos.

Netflix

- OK Google, play Stranger Things on Netflix

- OK Google, play Disenchantment episode 2 on Netflix.

News

- OK Google, watch the news.

- OK Google, watch technology news

- OK Google, watch Fox news.

- OK Google, next.

Google Photos

- OK Google, show me photos on TV.

- OK Google, show me photos of San Francisco on TV.

- OK Google, show me photos of mountains on TV

- OK Google, show me photos of the beach trip 2018 on TV

Security Camera

- OK Google, show me front door on my TV

- OK Google, what's on my backyard?

Weather  

- OK Google, show me the weather on my TV

- OK Google, show me the weather for tomorrow on my TV.

Calculator  

- OK Google, show me Google´s stock price on my TV

- OK Google, show me how many feet are in a mile on my TV.

Sport

- OK Google, show the score of the Capitals game on my TV

Translate and dictionary

- OK Google, show me how to say "Good morning" in French on my TV.

- OK Google, show me how to say "How are you?" in Spanish on my TV.

- OK Google, show me the definition of "perseverance" on my TV.

Weather

Ask for current weather (for your Google Home device address)

- OK Google, what's the weather?

Weather forecast

- OK Google, what's the weather tomorrow?

- OK Google, weather on Monday.

- OK Google, weather on weekend.

- OK Google, what's the weather next week?

Specific questions about weather / forecast

- OK Google, is it sunny today?

- OK Google, is it going to rain tomorrow?

- OK Google, should I take an umbrella?

Weather forecast for a specific location

- OK Google, weather tomorrow in Moscow?

- OK Google, will it rain tomorrow in St. Petersburg?
