---
title: Aprende a usar Google Assistant Comandos útiles y trucos
subtitle: Maximiza tu experiencia con el asistente virtual de Google
shorttitle: "Blogdown"
description: |
  Accede al [PDF](https://achalmaedison.netlify.app/blog/posts/2020-05-23-comandos-google-assistant/index.pdf)
abstract: |
  | Descubre cómo crear tu propio sitio web estático con Blogdown, una herramienta poderosa que combina R Markdown y Hugo. Aprende a usar comandos sencillos para personalizar, construir y alojar tu sitio web de manera fácil y rápida. ¡Comienza tu proyecto web hoy mismo!
keywords: [keyword1, keyword2]
categories:
  - Tecnología
  - Productividad
  - Asistentes Virtuales
tags:
  - GoogleAssistant
  - ComandosDeVoz
  - Automatización
citation:
  pdf-url: https://achalmaedison.netlify.app/blog/posts/2020-05-23-comandos-google-assistant/index.pdf
date: "05/23/2020"
draft: false  # Modo de borrador (false = final, true = borrador)
---

# Mastering Google Assistant: Basic Commands

Google Assistant is a powerful tool that can help you with various tasks using simple voice commands.
Here is a comprehensive list of basic commands to get you started with controlling your device, managing your schedule, and more.

## Stop and Pause

-   **Stop playing**
    -   "OK Google, stop."
-   **Pause**
    -   "OK Google, pause."
    -   "OK Google, resume."

## Control the Volume

-   "OK Google, increase volume."
-   "OK Google, volume up."
-   "OK Google, decrease volume."
-   "OK Google, volume down."

## Ask for Help

-   "OK Google, help."
-   "OK Google, what can you do?"

## Repeat the Last Phrase

-   "OK Google, repeat."

## Change Google Assistant's Voice

-   "OK Google, change your voice."

## Combine Commands

-   "OK Google, what is the time, and what's the weather?"

## Bluetooth

-   **Pair a Bluetooth device**
    -   "OK Google, pair Bluetooth."
-   **Connect to a Bluetooth device**
    -   "OK Google, connect."
    -   "OK Google, connect to my phone."
-   **Disconnect from a Bluetooth device**
    -   "OK Google, disconnect."
    -   "OK Google, disconnect from my phone."

## Calendar

-   **Hear information about agenda/Calendar**
    -   "OK Google, what's my calendar for today?"
    -   "OK Google, what's my agenda for Friday?"
    -   "OK Google, calendar for tomorrow."
-   **Add a calendar event**
    -   "OK Google, add an event to my calendar."
    -   "OK Google, add the meeting to my calendar for tomorrow at 5 p.m."
-   **How many days until holidays**
    -   "OK Google, how many days until Christmas?"
    -   "OK Google, how many days until New Year?"

## Calls and Messages

-   **Call a contact**
    -   "OK Google, call."
    -   "OK Google, make a call."
    -   "OK Google, call Eugene."
    -   "OK Google, call Eugene on speaker."
    -   "OK Google, find Eugene's phone number."
-   **Send SMS**
    -   "OK Google, SMS."
    -   "OK Google, text Eugene."
    -   "OK Google, text John 'Buy some milk.'"
    -   "OK Google, message to John 'Hello, John.'"
-   **Send a WhatsApp or Viber message**
    -   "OK Google, message Eugene via WhatsApp."
    -   "OK Google, message Eugene via Viber."
    -   "OK Google, message Eugene 'Hello, Eugene.'"
    -   "OK Google, WhatsApp John."
    -   "OK Google, Viber John."
    -   "OK Google, voice message to Eugene."
    -   "OK Google, voice message to Eugene via WhatsApp."

## Calculator

-   **Arithmetic**
    -   "OK Google, multiply 15 by 16."
    -   "OK Google, what's 15 times 16?"
    -   "OK Google, what is 15% of 50?"
    -   "OK Google, what's the square root of 42?"
-   **Unit Converter**
    -   "OK Google, how many meters are in a mile?"
    -   "OK Google, 10 inches in meters."
    -   "OK Google, how many grams are in a kilogram?"
    -   "OK Google, 5 liters in gallons."
    -   "OK Google, how many pounds in a kilo?"
-   **Currency Exchange Rate**
    -   "OK Google, how many dollars is a euro?"
    -   "OK Google, 15 US dollars in Russian rubles."
-   **Stock Exchange**
    -   "OK Google, what's the stock price of Apple?"
    -   "OK Google, how much does Bitcoin cost?"

## Cooking

-   **Named Timer**
    -   "OK Google, set chicken timer to 10 minutes."
    -   "OK Google, how much time is left for chicken?"
-   **Dish Caloricity**
    -   "OK Google, how many calories are in a beefsteak?"
    -   "OK Google, how many calories are in a glass of Cola?"
-   **The Nutritional Value**
    -   "OK Google, how much sugar is in Cola?"
    -   "OK Google, how much protein is in chicken?"
    -   "OK Google, how much vitamin A is in a carrot?"

## Dictionary

-   **Word Meanings**
    -   "OK Google, what is the definition of the word 'instant'?"
    -   "OK Google, what does the word 'mammal' mean?"
    -   "OK Google, find the definition of 'agila.'"
-   **Word Spelling**
    -   "OK Google, how do you spell 'ambassador?'"

## Easter Eggs

-   **Getting to Know Google Assistant**
    -   "OK Google, what are you?"
    -   "OK Google, what's your favorite color?"
    -   "OK Google, how are you?"
    -   "OK Google, do you have kids?"
    -   "OK Google, what's your quest?"
    -   "OK Google, tell me about your childhood."
    -   "OK Google, can you drive?"
    -   "OK Google, who made you?"
    -   "OK Google, where do you live?"
    -   "OK Google, what do you dream about?"
    -   "OK Google, do you have feelings?"
-   **Party Tricks**
    -   "OK Google, I need a poem."
    -   "OK Google, tell me a story."
    -   "OK Google, roll a dice."
    -   "OK Google, flip a coin."
    -   "OK Google, tell me a joke."
    -   "OK Google, sing a song."
    -   "OK Google, beatbox."
    -   "OK Google, tell me something I don't know."
    -   "OK Google, sing a lullaby."
    -   "OK Google, what am I thinking now?"
    -   "OK Google, surprise me."

## Email

-   **Send Email**
    -   "OK Google, email."
    -   "OK Google, send an email."
    -   "OK Google, send an email to Eugene."
    -   "OK Google, send an email to Eugene 'Buy some milk.'"

## Geography

-   **Country Facts**
    -   "OK Google, how many people live in Russia?"
    -   "OK Google, what's the capital of Austria?"
    -   "OK Google, Spain area."
-   **Facts About Oceans/Seas/Rivers/Lakes**
    -   "OK Google, biggest ocean."
    -   "OK Google, depth of the Pacific Ocean."
    -   "OK Google, the saltiest ocean."
    -   "OK Google, the longest river."
    -   "OK Google, what's the longest river in Russia?"
    -   "OK Google, deepest lake."
    -   "OK Google, the deepest lake in Canada."
-   **Discover Facts About Nature**
    -   "OK Google, why is the sky blue?"
    -   "OK Google, where does the rain come from?"

## History

-   **Historical Events**
    -   "OK Google, what happened during the Enlightenment?"
    -   "OK Google, when did World War 2 begin?"
    -   "OK Google, Olympic Games in the USSR."
    -   "OK Google, when was the Cold War?"

## Lists

-   **Add Item to the List**
    -   "OK Google, add bread to my shopping list."
    -   "OK Google, add milk and potatoes to my shopping list."
-   **Ask What's on List**
    -   "OK Google, what's on my shopping list?"
    -   "OK Google, my shopping list."

## Music

-   **Play Music on Google Music**
    -   "OK Google, play some music on Google Play."
    -   "OK Google, play jazz music on Google Play."
-   **Play a Google Music Playlist**
    -   "OK Google, play my Trance playlist on Google Play."
-   **Play a Song**
    -   "OK Google, play 'Can't Stop' on Google Play Music."
    -   "OK Google, play 'At The End' by Linkin Park."
-   **Play an Artist**
    -   "OK Google, play music by Taylor Swift."
    -   "OK Google, play One Republic."
-   **Play an Album**
    -   "OK Google, play the last U2 album."
    -   "OK Google, play 'Essential Classical' on Google Play."
-   **Control What's Playing**
    -   "OK Google, next."
    -   "OK Google, previous."
    -   "OK Google, repeat this song."
-   **Fast Forward or Rewind**
    -   "OK Google, skip forward 1 minute."
    -   "OK Google, skip back 1 minute."
-   **Play Music Based on Genre/Mood/Activity**
    -   "OK Google, play some fun music."
    -   "OK Google, play music for a workout."
    -   "OK Google, play songs for sleeping."
-   **Find the Song by Part of the Lyrics**
    -   "OK Google, play the song that goes 'Head out on the highway.'"
-   **Ask What's Playing**
    -   "OK Google, what song is this?"
    -   "OK Google, what song is playing?"
    -   "OK Google, what's this album?"
-   **Get Information**
    -   "OK Google, who sings the song 'Let It Go?'"
    -   "OK Google, who is in the band Daft Punk?"
    -   "OK Google, what year did Linkin Park release 'Hybrid Theory?'"

## Movies

-   **Today in the Cinema**
    -   "OK Google, what movies are playing tonight?"
    -   "OK Google, movie schedule."
-   **Movies Short Summary**
    -   "OK Google, tell me about the movie 'The Matrix.'"
    -   "OK Google, 'Blade Runner' duration

."

## Navigation

-   **Address and Business Search**
    -   "OK Google, where is my work?"
    -   "OK Google, what is the address of the nearest pharmacy?"
    -   "OK Google, where is the closest supermarket?"
    -   "OK Google, find a Chinese restaurant."
-   **Navigation**
    -   "OK Google, how do I get to the nearest gas station?"
    -   "OK Google, take me to the nearest hotel."
    -   "OK Google, navigate me home."
    -   "OK Google, show me directions to work."
    -   "OK Google, navigate me to 321 King's Street, London."
    -   "OK Google, how much time does it take to get to the hospital?"
    -   "OK Google, find the fastest route to the restaurant."
-   **Taxi**
    -   "OK Google, call a taxi."
    -   "OK Google, order a taxi."
    -   "OK Google, book an Uber to 321 King's Street, London."

## News

-   **Daily News**
    -   "OK Google, what's the latest news?"
    -   "OK Google, what's the news about Apple?"
    -   "OK Google, news about Canada."

## Places

-   **Find Business Hours**
    -   "OK Google, is the pharmacy open?"
    -   "OK Google, when does Starbucks close?"
-   **Search for Places and Businesses**
    -   "OK Google, where is the nearest grocery store?"
    -   "OK Google, where is the closest museum?"
    -   "OK Google, find me a pizza place."
    -   "OK Google, find me an Italian restaurant."

## Podcasts

-   **Play a Podcast**
    -   "OK Google, play the latest episode of 'The Daily.'"
    -   "OK Google, play 'The Joe Rogan Experience.'"

## Radio

-   **Listen to the Radio**
    -   "OK Google, play NPR."
    -   "OK Google, play BBC Radio 1."
    -   "OK Google, play 106.7 FM."

## Reminders

-   **Set Reminders**
    -   "OK Google, remind me to call John in 20 minutes."
    -   "OK Google, remind me to check the oven in 10 minutes."
    -   "OK Google, remind me to buy milk at 4 p.m."
    -   "OK Google, remind me to take out the trash tomorrow."
-   **Check Reminders**
    -   "OK Google, what are my reminders for today?"
    -   "OK Google, what are my reminders for tomorrow?"

## Smart Home

-   **Control Smart Lights**
    -   "OK Google, turn on the lights."
    -   "OK Google, turn off the lights."
    -   "OK Google, dim the lights."
    -   "OK Google, brighten the lights."
    -   "OK Google, change the living room lights to blue."
-   **Control Smart Thermostats**
    -   "OK Google, set the thermostat to 72 degrees."
    -   "OK Google, increase the temperature by 2 degrees."
    -   "OK Google, decrease the temperature by 2 degrees."
    -   "OK Google, set the thermostat to cool mode."
-   **Control Smart Plugs**
    -   "OK Google, turn on the coffee maker."
    -   "OK Google, turn off the fan."
-   **Control Smart Locks**
    -   "OK Google, lock the front door."
    -   "OK Google, is the front door locked?"
-   **Control Smart Cameras**
    -   "OK Google, show me the front door camera."
    -   "OK Google, show me the living room camera."

## Timers and Alarms

-   **Set a Timer**
    -   "OK Google, set a timer for 10 minutes."
    -   "OK Google, set a second timer for 5 minutes."
    -   "OK Google, set a chicken timer for 30 minutes."
-   **Set an Alarm**
    -   "OK Google, set an alarm for 6 a.m."
    -   "OK Google, set a daily alarm for 7 a.m."
    -   "OK Google, set a one-time alarm for 9 p.m. on Tuesday."
-   **Check and Manage Alarms**
    -   "OK Google, what are my alarms?"
    -   "OK Google, delete my 7 a.m. alarm."
    -   "OK Google, cancel all alarms."
-   **Stop Alarms**
    -   "OK Google, stop."
    -   "OK Google, snooze for 10 minutes."

## Weather

-   **Current Weather**
    -   "OK Google, what's the weather like?"
    -   "OK Google, what's the weather?"
    -   "OK Google, what's the temperature?"
    -   "OK Google, what's the weather in London?"
-   **Weather Forecast**
    -   "OK Google, what's the weather forecast for tomorrow?"
    -   "OK Google, will it rain tomorrow?"
    -   "OK Google, what's the 7-day weather forecast?"
    -   "OK Google, what's the weather this weekend?"

By using these commands, you can efficiently interact with Google Assistant to make your daily tasks easier and more convenient.

{{< include ../../_contenido-inicio.qmd >}}

{{< include ../_contenido_posts.qmd >}}

{{< include ../../_contenido-final.qmd >}}
