---
title: "Encuesta Nacional de Intensiones de Siembra de la Campaña Agrícola 2022-2023"
# Información del Autor
author:
  - name: Edison Achalma # Nombre del autor
    url: https://achalmaedison.netlify.app # URL del autor
    affiliation:
      - id: draa
        name: Dirección Regional de Agricultura - Ayacucho # Afiliación del autor
        department: Dirección de Información Agraria y Estudios Económicos
        # address: Portal Independencia N 57
        city: Ayacucho
        region: AYA
        country: Perú
        postal-code: ~
    # affiliation-url: https://www.gob.pe/unsch # URL de la afiliación del autor
    orcid: 0000-0001-6996-3364 # ORCID del autor
    email: elmer.achalma.09@unsch.edu.pe
    attributes:
      corresponding: true
      equal-contributor: true
      deceased: false
    # Los roles son opcionales. Seleccione de la taxonomía CRediT: Contributor Roles https://credit.niso.org/
    # conceptualización, curación de datos, Análisis formal, adquisición de financiación, investigación, metodología,
    # administración de proyectos, recursos, software, supervisión, validación, visualización, redacción, edición.
    roles:
      - conceptualización
      - redacción
date: '2022-07-13'
slug: mwas-repurposed-covid19-meds 
categories:
  - Research 
abstract: 'Reporte de encuesta'
# doi-title: Scientific Reports (DOI)
# doi: "10.1038/s41598-022-24218-1"
subtitle: Este trabajo está orientado a determinar la superficie de siembra de la Campaña Agrícola 2022-2023 y tiene la finalidad de planificar las siembras para el normal abastecimiento de productos agroalimentarios en beneficio la población en genera
# description: Description text example
# abstract: ''
links:
- icon: file-richtext-fill
  name: Publication
  url: https://www.agroayacucho.gob.pe/inicio/diaee-2/#dearflip-df_2255/37/
- icon: file-earmark-pdf
  name: PDF
  url: enis-2022-2023.pdf
filters:
  - lightbox
lightbox: auto
---

## Abstract

La Encuesta Nacional de Intenciones de Siembra (ENIS) se viene ejecutando en forma
continua desde la Campaña Agrícola 2002-2003, constituyendo una valiosa fuente de información,
referente a las estimaciones de siembra de los principales cultivos transitorios de importancia
nacional y regional, para los productores agrarios de la región y para la oportuna toma de
decisiones de la política sectorial, así como, para tratar de evitar los desbalances en la producción
acorde a la oferta y demanda.
Este trabajo está orientado a determinar la superficie de siembra de la Campaña Agrícola
2022-2023 y tiene la finalidad de planificar las siembras para el normal abastecimiento de
productos agroalimentarios en beneficio la población en general.

