---
title: El capitalismo ¿Cáncer de nuestra era?
subtitle: Reflexiones sobre la pobreza y la desigualdad en un sistema económico depredador e injusto.
description: |
  En la actualidad, el capitalismo es uno de los sistemas económicos más criticados por sus impactos negativos en la sociedad y el medio ambiente.
categories:
  - Política
  - Economía
tags:
  - Capitalismo
  - Desigualdad
  - Pobreza
citation:
  pdf-url: https://achalmaedison.netlify.app/docs/blog/posts/2023-03-03-el-capitalismo/index.pdf
date: "04/29/2023"
draft: false  # Modo de borrador (false = final, true = borrador)
---

En 1987 el mundo tenía 1.5 billones de pobres (con menos de 1 dólar al día) en 2015 son 1.9 billones. El índice internacional de pobreza se ha modificado varias veces en nombre de buenas campañas de relaciones públicas para el world bank.

El índice actual es 1.25 $/día, ajustado a inflación es menor que en ajustes anteriores. Mas allá de los defensores del capitalismo sean las personas más ignorantes y ciegas de su privilegio de la modernidad, nadie puede realmente vivir con 1.25 /día.

En USA el valor mínimo para sufrir malnutrición seria 4.05 $/día. En India el 60% de las personas que viven con el dólar por día sufren desnutrición. Porque esto es obsceno y barbárico y culpa de un modelo económico abusivo, corrupto, depredador e injusto.

Porque el mundo produce 1.5x la cantidad de comida necesaria para alimentar el mundo. Además, el 30% de dicha comida se desperdicia previa a su uso. Esto es solo una variable analizada fríamente sobre por qué el capitalismo es el cáncer de nuestra era.

Y los que los defienden, los payasos más ignorantes de la historia. Antes que me digas socialista, porque tu cerebro solo entiende el mundo en blanco y negro. No tengo nostalgia del pasado ni quiero vivir en Venezuela, Cuba, Rusia, China, Noruega o Finlandia.

Ese antagonismo asustador es para niños asustados con miedo al comunismo como si fuera el monstruo debajo de tu cama. Usan esas historias de países fracasados para hacerte creer que no existe alternativa (TINA: there is no alternative).

El primer paso para crear una alternativa es admitir que la que tenemos es un mierda que nos está destruyendo, física, mental y terrestremente. Y que no tenemos ninguna antigua a la cual volver. Ojalá y más gente abra los ojos antes que sea demasiado tarde.

Antes que hables del libre mercado, pregúntate desde tu lógica libertaria por qué no sería legal la necrofilia o la expropiación de órganos por empresas. (El capitalismo se puede poner muuuuucho peor).