---
title: ¿Cuáles son las cualidades de los servidores públicos?
subtitle: Cualidades de los servidores públicos.
description: |
  Este artículo explora las cualidades esenciales que deben tener los servidores públicos. Desde la amabilidad hasta la serenidad, cada una de estas características desempeña un papel fundamental en el desempeño efectivo de los servidores públicos.
categories:
  - Gestión Pública
tags:
  - Amabilidad
  - Juicio astuto
  - Habilidades a prueba de futuro
  - Justicia
  - Tenacidad
  - Un sentido del deber
  - Un toque de rebelión
  - Motivador
  - Promueve el diálogo
  - Serenidad
  - Enfocado en resultados
  - Sabe delegar
date: "05/11/2023"
---

# ¿Cuáles son las cualidades de los servidores públicos?

## Amabilidad

Con demasiada frecuencia, equiparamos la amabilidad con no ser asertivo o incluso ser agresivo. Hay tantas personas llenas de ideas brillantes. Pero aquellos con la amabilidad de crear formas inclusivas y poderosas de diseñar, dar forma, entregar y evaluar esas ideas brillantes son las que siempre quiero conectar y aprender.

## Juicio astuto

Es la capacidad de ver a través de alguien. El servidor público está en una posición única: está obligado por la maquinación de un maestro político. Tiene que entregar a caras desconocidas. Uno tiene que ver a través de los velos, ya que hay muchas máscaras que usan las personas. Para un servidor público, esto es muy importante: que entiendan a qué máscara le están hablando. Si se entiende eso, se resuelve muchos misterios y desamores. Los siguientes pasos son imaginación, trabajo duro, trabajo en equipo y una mente abierta.

## Habilidades a prueba de futuro

La cara del gobierno está cambiando: el cambio no es solo en los poderes geopolíticos, sino en los crecientes poderes de las ciudades, del sector privado, de la sociedad civil. Se necesita repensar el servicio público en general. ¿Cómo capacitamos a los departamentos gubernamentales para estar preparados para un futuro complejo y cambiante y las necesidades y vidas cambiantes de los ciudadanos? Necesita un replanteamiento, no solo de habilidades y servicios y programas, sino del tipo de talento y habilidades para los que reclutamos.

Los servidores públicos deben ser considerablemente más expertos en datos y tecnología para comprender los poderes y las oportunidades que ofrece la tecnología emergente. Necesitan la capacidad de ir más allá de los programas y políticas "marcar la casilla" y adoptar enfoques y socios innovadores.

##  Justicia

Lo que hace a un bueno a un servidor público, particularmente en términos de políticos y funcionarios políticos, es la calidad de operar desde una premisa de ideas y principios, no intereses individuales y agendas partidistas.

## Tenacidad

La vocación civil y el compromiso requieren el deseo constante de mejorar la calidad de vida de la sociedad, la situación actual y las oportunidades futuras. Todos buscan lo mejor para sus familias, pero un funcionario busca lo mejor para todas las sociedades y países.

Necesitan tenacidad y consistencia para lograr resultados prácticos para mejorar la vida de las personas; para construir esa visión de una sociedad mejor.

## Un sentido del deber

Se está atravesando un proceso doloroso para descubrir la corrupción en el Perú en este momento y, en el fondo, casi siempre hay un servidor público que no puede resistir alguna forma de soborno. Obviamente, se debe ofrecer un soborno antes de que pueda ser aceptado, pero aquí es donde entra en juego la integridad como valor para los servidores públicos.

Entonces un servidor público siempre debe tener en cuenta al "servidor" en el servidor público. En nuestro contexto, una posición del gobierno a menudo se ve como una posición de estado, y no una de servir al bien público.

## Un toque de rebelión.

Los servidores públicos más efectivos son aquellos que desafían constantemente. Desafían sus propias ideas y prejuicios, desafían la forma en que "siempre se ha hecho" y desafían a los líderes de pensamiento de alto nivel.

Los realmente efectivos colaboran con socios que también desafiarán el statu quo. El desafío y la colaboración conducen a la innovación, y eso es lo que nos ayudará a todos a resolver algunos de los problemas más apremiantes de nuestro tiempo.

## Motivador

Ser motivador es un factor relevante para que las personas que trabajan en el sector público vayan a cumplir sus funciones de la mejor manera y puedan ayudar a que los objetivos institucionales se cumplan en la fecha programada.

## Promueve el diálogo

El diálogo es básico en el sector público para llegar a consensos rápidamente. Un servidor público con esta característica será capaz de destrabar muchos cuellos de botella con una llamada o conversación cara a cara para sacar adelante sus proyectos.

## Serenidad

En situaciones extremas y de crisis, el funcionario público moderno debe saber guardar la calma para no transmitir la desesperación a sus compañeros. Así, podrá lidiar con las presiones del corto y largo plazo gracias a una toma de decisiones inteligente.

## Enfocado en resultados

Esta es una cualidad imprescindible pues todas las entidades públicas y sus funciones están hechas para cumplir una serie de objetivos. Si el servidor público no llega a su trabajo con la idea de alcanzarlos entonces no ayudará al desarrollo general.

## Sabe delegar

Una sola persona no va a poder acumular toda la carga de una entidad. Por eso, es vital saber delegar, crear una línea horizontal de trabajo para empoderar a su equipo, motivarla y, como consecuencia, cumplir o superar los objetivos.
