---
title: Seminario de filosofía del presidente Gonzalo
subtitle: Notas 1987.
description: |
  Comité Central del Partido Comunista del Perú llama a seguir sembrando revolución en el día del proletariado.
categories:
  - Política
tags:
  - Partido Comunista del Perú
  - Revolución
  - Día del proletariado
author: Comité Central Partido Comunista del Perú
date: "04/29/2023"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
---

## SEMINARIO DE FILOSOFÍA DEL PRESIDENTE GONZALO (NOTAS 1987)

Textos de referencia:

- Introducción a la dialéctica F. Engels.
- La familia, la propiedad privada y el Estado F. Engels.
- La transformación del mono en hombre a través del trabajo F. Engels.
- Carlos Marx de Lenin Obras escogidas Tomo II.

Muchos han sostenido que lo que forma la mente del hombre son las matemáticas, ya no se puede
pensar así. La lógica otros. Ni la matemática ni la lógica son sistemas que forman la mente del
hombre. Es la filosofía, proceso del conocimiento a través de distintas etapas y modos de
producción.

Ocupándose de las leyes que rigen el desarrollo del hombre Lenin llegó a establecer que la filosofía
era una necesidad eminentemente política. “el meollo de la ideología es la filosofía”. Lenin se
abocó a estudiar todo el proceso de la filosofía desde el punto de vista marxista. Estudió la ciencia
de la lógica de Hegel.

- “Cuadernos filosóficos” Lenin.
- IV tomo “Acerca de la práctica” y “sobre la contradicción”. Pte. Mao.

Sin filosofía no hay partido.

**Proceso de la filosofía:** desechar el criterio de que la filosofía solo se va a dar a partir del mundo
griego. Los estudios posteriores demuestran que eso es un prejuicio, desprecio por el pensamiento
de otros pueblos. Proceso en China, la India. Conforme la civilización avanza, los pueblos se
esfuerzan por conocer el fondo de las cosas, el porqué de las cosas, Egipto, Mesopotamia, pueblo
Hebreo, donde hay un proceso de desarrollo, se sigue planteando que es una pre-filosofía, se niega
el proceso de desarrollo desde los tiempos más iniciales. Las propias religiones: los egipcios
plantean que las aguas son el principio primordial, un símbolo de vida, pero no saben de dónde
viene el Nilo, el Nilo al expandirse deja algunas islas y en ellas se desarrolla el espíritu. Plantean
dos cuestiones: Espíritu y Materia. Lo importante es que siempre planteaban un principio que es
materia.

Los griegos son los que nos plantean una filosofía más desarrollada, ligada al proceso de mercado,
la aparición de la moneda y ligada a la ciencia. Tales, predice el primer eclipse. Los egipcios sabían
cuestiones matemáticas por práctica, son los griegos los que explican y demuestran los hechos.
Avance en el conocimiento científico y la lucha de clases de los esclavistas, agudización de la
lucha entre comerciantes y los agricultores, “democracia griega que tiene un proceso dictatorial
antes de la democracia. Se nos pretende hacer ver (que) la filosofía está desarrollada al margen de
las clases, siglos VII y VI a.c.

**Escuela materialista.** Arge: origen, el porqué de las cosas es el origen: el comienzo de las cosas
son las aguas, es la ley que todo deriva. Caos original y orden en las cosas. Esto ya lo habían dichlos egipcios. Hizo indagaciones y encuentra en las islas conchitas (fósiles). Otro pensador va a
decir que el origen es el aire, siempre un origen material. Heráclito: plantea que el origen de las
cosas es el fuego, previa: realidad material son pues materialistas. La guerra es
el origen de todas las cosas, la lucha de dos contrarios y de esa pugna tenemos un proceso constante
de desarrollo, todo es un permanente discurrir, nadie se baña dos veces en la mismas aguas. Aquí
tenemos la dialéctica. Intuiciones geniales. De ellos solo nos han quedado
frases, nada más. Aristóteles historia todo esto. Intuiciones geniales no fundamentales. La
contradicción de la filosofía es contra la religión. Se desgaja de la religión. Aparece el idealismo.
Parménides niega la dialéctica, surge como contraposición a Heráclito: tiene dos cabezas una
afirma otra niega, no razona. Plantea que el origen de todas las cosas es el ser: es el ser absoluto,
lo abarca todo, las cosas existen porque participan del ser.

El ser no tiene movimiento, si se desplazase sería el no ser. Los hombres en esa época no podían
refutarle.

El materialismo parte de la materia previa y de un proceso del conocimiento. Lo primero son los
materialistas, los idealistas son posteriores.

**Demócrito:** gran materialista. Teoría de los átomos: lo que no puede partirse. Una mínima
instancia material. Todo lo que existe son pequeñas partículas que no pueden partirse, eternas y en
continuo movimiento. Así refuta las teorías de los idealistas de Parménides de la divisibilidad
infinita que llevaría a lo no existencia. No es hasta 1900 que se refuta la indivisibilidad del átomo.

El conocimiento es un reflejo de los átomos en la cabeza. Los efluvios se entrecruzan y esto se
refleja en nuestra cabeza de ahí tenemos el error. Plantea que el hombre se desenvuelve
socialmente. Parte integrante de las Polis. Refleja lo que se ve en su propia ciudad. La
esclavitud es nociva porque rebaja al hombre, porque envilece al ser humano, no le permite dar lo
mejor que tiene de sí, es la libertad lo que corresponde. El hombre debe ser libre, entra al campo
de la moral, sabría que le permitiría vivir libremente. El más grande exponente del
materialismo en la antigüedad.

El materialismo siempre se ha desarrollado con una comprensión y un respeto al hombre. Su
pensamiento era nocivo para la sociedad y los criterios de la clase dominante, todos los criterios
idealistas están ligados a los comerciantes y los esclavistas. Los sofistas plantean que
el hombre puede ser educado y así elevarse. El hombre es la medida de todas las cosas. En Sócrates
se ve como los griegos eran sumamente sociales, el individualismo no estaba desarrollado.

**Platón:** ligado a la aristocracia, muy acaudalado, sistematiza todo el pensamiento idealista.
Sostiene que hay una apariencia y una realidad, que los sentidos son engañosos, que la apariencia
es idea y el mundo es materia:
La realidad de las cosas participan de las ideas. Plantea una trinidad de las ideas bien, belleza,
verdad y estas tres están sustentadas por el ser. Teoría de la coparticipación de las ideas. Plantea
el comunismo platónico que tiene un antecedente en Egipto que es un comunismo reaccionario. El
entiende que la propiedad genera luchas. Para él el ordenamiento democrático era nocivo, pensaba
en un gobierno de élites. La educación para él era nociva. Lo entiende porque la aristocracia estaba
siendo atacada, destruida por los comerciantes. Sociedad: conjunto de trabajadores conforme a los
que se van educando se van seleccionando, trabajadores, guerreros, etc. Y queda un conjunto de
élites (fascismo) la música porque corrompen. Destruyó todo lo que llegó a su alcance de
Demócrito.

**Aristóteles:** discípulo de Platón. Nos ha informado de todo lo que pensaban los materialistas,
critica a Platón y va a basarse mucho en los conocimientos científicos y sociales de la época.
Aristóteles se basaba en el conocimiento científico, critica a Platón:

En las cosas existen pero tiene una realidad material y una forma, si no tuvieran la forma entonces
se confundirían. Existen las cosas porque tienen una materialidad y una forma. Llega al idealismo
desde una base real, ha metido la idea en la realidad. Comienza a manejar los conceptos y las
formas, esencia: una sustancia y una esencia, hay una realidad primaria, una esencia superior que
imprime el movimiento, porque existe un motor primer móvil, dios, la palabra que se conoce a sí
misma. Llega al idealismo a partir de un nudo de arterias. Las cosas existen realmente no se pueden
negar pero llega al pensamiento que se piensa a sí mismo, y ese pensarse a sí mismo es lo que ha
puesto en movimiento la realidad.

Como realidad concreta la materia no tiene movimiento, es la idea lo que se mueve, primen móvile
(primer motor). Dialéctica conceptual. Lo positivo que tiene es que existe la materia. Es otra forma
de platonismo.

**Escuelas:**
Los romanos nunca lo pudieron superar, el neoplatonismo como decadencia que llega a la mística
(Plotino). La iglesia no puede afiliarse con el platonismo.

**Medievo.** Se comienza a desenvolver la filosofía como reivindicación de la Razón. Aparte de los
árabes, es a través de ellos que se empieza a conocer la filosofía griega y se comienza a conocer el
aristotelismo. Los árabes llegan a desarrollar un criterio materialista, llegan a
diferenciar la filosofía de la teología. Filosofía se ocupa de la tierra y la teología del cielo. Los
árabes y los hebreos son los que tienen influencias.

**Realistas y nominalistas.**
Los realistas aplican las tesis aristotélicas, realidad de las cosas y las ideas también existen
independientemente.
Los nominalistas no son sino bocas vacías, sin contenido real, son derivaciones extraídas de las
cosas. Quienes se enfrentan son las ideas religiosas.

**Pedro Abelardo:** comienza a manejar la lógica formal, creador de la lógica deductiva. Maneja la
lógica de forma dialéctica (debate, discusión). Tiene mucha importancia para el pensamiento
francés. Ataca a la religión. Marx considera que el nominalismo tiene mucha importancia.

**Duns Scotto** tiene mucha importancia, era franciscano. La raíz del materialismo moderno está
en este personaje: ¿cómo combatir la religión? La comunión.

¿Cuántas veces y cuántos hombres comulgan? Entonces ya no quedaría cuerpo de Cristo. Todos
los que se oponían eran muertos, época muy violenta, muy dura. Se nos quiere presentar a los
filósofos como hombres de pupitre, la realidad no ha sido así, la puñalada y el
veneno ha sido la forma de debatir en filosofía.

**Tomás de Aquino:** Tomismo, (agustinismo –neoplatonismo-), italiano que entra a dominico.
Discípulo de Alberto Magno: plantea que racionalmente se puede llegar a comprender la religión
católica. La razón no se contrapone a la teología. Se basa deformando a Aristóteles, no es un
desarrollo de Aristóteles, es mucho más bajo. Su obra más importante es el Ente y La Razón
(Bertrand Russell) en vida fue perseguido por la iglesia y es el fundamento. (OCCAMO lo
que hizo junto con Scotto fue rebatir el tomismo).

El proceso filosófico se empieza a desenvolver con la burguesía (Francisco Bacon) reivindica la
experiencia (“nuevo órgano”). Lo que hace es desarrollar una lógica inductiva que va a servir a
la ciencia. Plantea que su pensamiento abarca el pensamiento de los hombres (reconoce a la
teología pero aparte).

**Descartes (1596-1650)** fue discípulo de los jesuitas. Comprendió que lo que en un pueblo se
afirmaba en otro se negaba, que la ciencia no tenía sólidos fundamentos (coordenadas cartesianas
que permiten llevar la geometría al análisis algebraico). Era estudioso de la física
del mundo, de la materia, lo que retoma es el pensamiento de Demócrito. El es materialista en ese
campo. Plantea la duda metódica (no es el escepticismo que cuestiona el conocimiento, no
confía en el conocimiento) hay que dudar para llegar a un conocimiento evidente, plantea el engaño
de la vista. Los sentidos engañan, no se puede creer en los sentidos, pero hay algo que
es evidente YO. No puedo dudar que yo existo, hay una verdad indubitable. Yo dudo luego existo.
Cualquiera que sea lo que pueda presentar a la realidad, existe algo innegable.
Yo pienso, luego existo. Verdad evidente ante cuya existencia no hay duda. Existo yo y mis
pensamientos. La realidad la va viendo a través de sus pensamientos.

Tengo las ideas, es porque existe dios y es quien ha dado todo. Todo existe porque existe dios.
Cuando desarrolla la ciencia es materialista pero cuando desarrolla ideas metafísico, pone
como pivote de la filosofía el YO, de aquí para adelante empieza a fundarse el pensamiento
burgués.

Escuela materialista contraria que toma a Demócrito.

Filosofía Alemana: Leibniz, Kant y Hegel.

Siglo XVII- XIX (1830). 150 años más o menos.

El luteranismo: limpia los establos de la iglesia.

Alemania da el más avanzado pensamiento de la escuela idealista. Leibniz: gran matemático.
Desarrolla la lógica, replantea la lógica de Aristóteles. No difundió sus pensamientos. Desenvuelve
un racionalismo. Es posible un análisis lógico. Lógica con símbolos para manejarla como análisis
matemáticos. Conjunto de axiomas que siguiendo un cálculo se pueden resolver todas las verdades
absolutas. Teoría de las mónadas: entidades cerradas. Se comunicaban a
través de una ventanilla, ideales, auto-movimiento. Problema de dinámica, pero esto es conceptual
porque son idealistas. Se dedica a analizar el conocimiento humano, liga la matemática y la física.

**Kant (1724-1804).** Se centra en el problema del conocimiento. Crítica de la razón pura. Plantea
que existe la realidad pero como fenómeno, lo que aparece. Lo que la luz muestra. Establece una
diferencia entre los fenómenos. Existen las cosas una parte que aparece y otra, la cosa en sí, que
no aparece. Existe la materia pero que no se la conoce. Establece relación entre el sujeto que
conoce y el objeto conocido, pero hay una parte que no se conoce. Analizando lascosas tenemos
unas sensaciones que las capto a través de mi sensibilidad.
Mundo, Hombre (alma), Dios Sistema completo del conocimiento
Elabora conceptos

**Categorías:** sistema lógico de conocimiento. Sólo conozco los fenómenos escapa a mi
conocimiento la cosa en sí, el conocimiento viene a ser una elaboración de la razón pura (R.P.)
elaboración entre el sujeto y el objeto (cosas) el sujeto es lo más importante. Hay una realidad que
puedo conocer y otra que no puedo conocer. La cosa se deja conocer.

Posterior a Kant se desarrolla el neokantismo que lo que hace es disolver la cosa en sí, la cosa en
sí es una elaboración de la cosa en sí. Se pasa de un idealismo a un ultra-idealismo. Kant ha llegado
a conocer por el entendimiento. Crítica de la razón práctica: cuando analiza el alma llega a pensar
en la libertad y ésta sólo se puede alcanzar en dios. La libertad el alma y el
regazo de dios. Ordena la comprensión del conocimiento y expresa los límites del idealismo
(razón) ¿Por qué se plantea que dios existe? Porque para explicar que todo tiene comienzo y fin se
busca la causa y esta causa es dios, pero al plantear que dios es la causa ¿ cuál es la
causa de dios?. El mismo refuta la existencia de dios.

**Hegel:** se plantea qué es lo anterior. Lo que pretende Kant es conocer la realidad a partir de su yo,
no centra en lo objetivo. El problema es partir de lo objetivo, analiza el proceso de la filosofía,
pensaba que todos los filósofos eran anteriores a él. Todos los demás pueblos para él no existían,
no eran nada. Desarrolla una teoría de la dialéctica que permitía la comprensión de todo el proceso
de la materia (su problema es que era idealista). El proceso se desenvuelve por contradicción y al
desenvolverse genera el problema de cantidad y calidad, apariencia-realidad. Entendía la dialéctica
como proceso de contradicción entre conceptos, ideas. Va a negar la aplicación de su propia
dialéctica. Plantea que existe una gran idea absoluta. Esa gran idea es la realidad
objetiva, cuyo proceso es contradicción a nivel de ideas solo. Muy parecido a Aristóteles pero
sin partir de la materia. Esta idea enjuiciaba por el propio proceso de contradicción a la materia.
Siendo el propio espíritu comienza a desenvolverse hasta generar al hombre y el espíritu se
hace autoconciencia, el espíritu se ha negado. El hombre: sociedad, conocimiento, ciencia, arte,
religión, nación y luego genera Estado. El Estado se convierte en gran transformación que luego
se convierte finalmente en Espíritu, dios. Idea Absoluta:

Tiene una comprensión de todo el desarrollo materialista pero es idealista. Dos partes. Su
idealismo, desechable y materialismo que es asumible.

Proceso materialista en Francia Diderot. Materia eterna, no tiene comienzo ni fin, llega a plantear
que hay un auto-movimiento interno que impulsa la materia, pero no explica porqué. Pero el
antecedente de la filosofía marxista es la filosofía clásica alemana. Muerto Hegel hay
una división, unos comienzan a criticar el idealismo de Hegel, el que interesa es Feuerbach, critica
el idealismo de Hegel pero no diferencia el materialismo del idealismo de Hegel. Lo que le lleva
a desechar a Hegel. Fenómeno de enajenación ante la religión (la alienación,
enajenación, es una palabra de Hegel) no es una tesis de Marx, diferencian al Marx joven del
amargo. Marx la desecha porque la solución es la revolución, la emancipación.

Hegel: el trabajo extrae al hombre de su esencia de ser pensante, de ser nacional.

Marx analiza las causas de la enajenación.

Feuerbach plantea que ante la enajenación el centro es el hombre no dios. La relación se entiende
por el amor, el cáritas (la caridad), de ver por el otro, maternidad, posición subjetivista, cómo se
relaciona un yo con otro yo. Cristianismo sin Cristo. Lo importante es la crítica materialista.
Marx y Engels llevan a una lucha contra el individualismo de Feuerbach.

Marx y Engels van a desarrollar el proceso filosófico marxista. Marx desarrolló y Engels difundió.
Las tesis sobre Feuerbach constituyen la base:

1o defecto de todo materialismo anterior: no haber tenido en cuenta la práctica. El materialismo
anterior se había desarrollado en el empirismo o ver la realidad como algo
pasivo, no se comprende como la materia actúa y como el hombre a través de su trabajo cambia la
realidad (captación de la realidad). Todo empirismo es una posición burguesa. Postula:
comprender la realidad y transformarla.

2o Práctica y verdad, es en la práctica como prueba de verdad. Marx critica y Feuerbach, nunca
llegó a concebir la captación sensorial como capacidad transformadora. Este había diluido la
esencia religiosa en la esencia humana, un cristianismo sin Cristo, la incapacidad de comprender
el mundo social. Relaciones sociales.

3o la vida social es esencialmente práctica. La mente humana esta descarriada por un conjunto de
misticismos. Sólo comprendiendo la práctica se puede barrer con el misticismo. Como no
comprenden la práctica lo llama materialismo contemplativo. Sociedad civil: a lo máximo que
llegó a avanzar fue al estudio de las instituciones, cual es la raíz que la sustenta. Transformar el
mundo: los filósofos no han hecho más que contemplar el mundo pero el problema es
transformarlo.

Con este documento deslinda los campos.

Ajuste de cuentas con sus anteriores pensamientos en una posición nueva. Se plantean así nuevos
criterios para formar la nueva ideología. Se plantea el proceso económico de la sociedad. Se
plantea el comunismo, cómo la 1a gran revolución en el mundo, pues todas las
anteriores fueron la sustitución de una clase por otra.

Toda la filosofía en su largo recorrido había desarrollado una teoría sobre la dialéctica, así como
sobre el materialismo. Critican con justa razón el Medievo. Una disputa que quería resolver las
cuestiones sin ver a la realidad. Ellos vieron bien los hitos del desarrollo. Afirman
su posición rotunda materialista. El acceder al materialismo demanda como un proceso en
movimiento derivado de la contradicción.

Althusser niega que Marx y Engels hayan tomado la dialéctica de Hegel. Plantea que primero se
desarrolla la ciencia y luego se produce el salto.El descubrimiento de Marx y Engels es el
materialismo histórico porque se funda la teoría materialista de la historia y después el
materialismo dialéctico. Según él estaba pendiente el desarrollo de la filosofía marxista. Es una
estupidez de principio a fin.

Platón y Kant son idealistas. Niega el proceso científico que se desarrolla desde el siglo XVII.
Desde finales del siglo XVI se pensaba que la tierra era algo que cambia, una forma de
movimiento. Proceso dialéctico. Química: no hay una muralla china entre la química orgánica y la
inorgánica. Biología: se descubre la célula, en los animales se ven formas transaccionales: como
eslabones. Teoría de la evolución. Así la ciencia rompe con la metafísica como procesos,
desarrollos. Esto no lo puede negar Althusser. Así la ciencia demandaba una explicación dialéctica.
Hegel había puesto el proceso dialéctico en la cabeza. Marx lo que hace es ponerlo en la materia.
Antes nunca fue hecho esto. El materialismo dialéctico es capaz de entrar en el conocimiento y la
transformación al actuar el hombre en la materia. Se cuestiona el carácter científico del marxismo,
la materia se transforma derivado de la práctica.

La ideología que han generado las clases explotadoras es invertida porque da una explicación
idealista de la historia. Nuestra ideología es científica porque es un reflejo real verdadero de su
práctica y su carácter de clase. Las teorías de Althusser llevan a un nuevo surrealismo y lo que
cabe es fundir la teoría kantiana y la de Spinoza. Se toma un racionalismo burgués y un idealismo
burgués. Este proceso tiene un trayecto de 2500 años, tienen un sólido fundamento
histórico en lo que se ha recogido lo mejor y resulta en el Marxismo-Leninismo-Maoísmo. La
aplicación del materialismo dialéctico da pie al materialismo histórico y a la comprensión
científica de la sociedad.

Ha habido un proceso para demostrar los fundamentos económicos de la sociedad. “El marxismo
lo que hace es criticar económicamente a la sociedad” dicen los que lo atacan. De la base
económica y la sociedad generan la ideología. No se ha dejado el problema de las ideas y la acción
que las sustenta.

Dialéctica: Engels es quien se ocupa de esta cuestión: tres leyes. Unidad y lucha de la
contradicción, el salto y la negación de la negación. Comprendieron que la 1a era la principal.
Si no hubieran entendido la dialéctica no hubieran llegado a poder desarrollar EL CAPITAL. Noes
un círculo, el marxismo es un proceso dialéctico que seguirá desarrollándose. Nos deslinda con
todos los procesos filosóficos que son cerrados.

Hegel es inconsecuentemente dialéctico y nosotros somos consecuentemente dialécticos. Esto es
la más grande revolución había en la historia de la humanidad. Filosofía marxista que sienta las
bases del desarrollo, nunca podrá agotarse el conocimiento, es un proceso que va más y más
acercándose a la verdad y desechando nuevos errores. Negaciones del marxismo: este fenómeno
ha sido constante. En materialismo y Empiriocriticismo, Lenin enarbola y
defiende al marxismo y lo desarrolla. Teoría del reflejo. Conjunto de reflejos que generan la
conciencia. El reflejo es una característica que es una característica de la materia, acción y
reacción. La conciencia viene a ser un largo proceso de la característica de la materia. Los
átomos. En el año 1900 un físico alemán plantea que existe una cantidad pequeñísima de materia
necesaria para dar un salto, teoría de los cuantos, con esto se abre la teoría nuclear.
Einstein lo que hace es una nueva teoría del espacio tiempo.

Newton:
Hay dos absolutos como entidades inseparables, lo que plantea es que espacio y tiempo son
relativos. Los experimentos demostraban que al producirse altas velocidades se producía una
reducción. El problema es que el tiempo y el espacio varían según la velocidad, dos absolutos se
convierten en dos relativos. Gravedad dos materias que se mueven en sentidos más amplios. Física
cuántica que rompen el átomo, niegan la materia, Lenin dice que estamos empezando a conocer
las 1a partículas. La materia en movimiento tiene forma cuantitativa y cualitativa, estamos viendo
nuevas formas de la materia porque la materia es eterno movimiento. Lenin rechaza que la materia
se disolvía.

Carácter partidista de la filosofía y la lucha contra el Empiriocriticismo. La física cuántica va a
dar campo a que se niegue el materialismo. Si conocemos la velocidad del electrón no conocemos
su ubicación, de esta manera se niega la causalidad: esta tiene dos acepciones, expresa la
correlación entre una causa y un efecto la otra es el problema de la previsibilidad. Se ha confundido
causa efecto con la previsibilidad, pero la causa efecto sigue existiendo. Al basarse en la
previsibilidad niegan lo anterior. Entonces lo que hemos encontrado es la casualidad y lo que se
ha descubierto es otra forma de la materia. Nuevas modalidades de la
materia, nuevas formas.

Dos líneas paralelas se juntan del lado interiores suman menos de dos rectos. V. Postulado.
Presupuestos. Geometría de las líneas paralelas. (Triángulo) 180o, durante muchos siglos se
consideró que esta era la única geometría.

Gauss planteó que no tiene demostración, quien cambie este postulado genera otra geometría.
Cuando viene la cónica encuentran que es inadecuada. Geometría de Reirmer. 180o geometría de
latbochesky-bauyeic. (Dibujo).

Antes hablábamos de un espacio plano otro curvo y otro cóncavo. Así la materia tiene muchas
manifestaciones. Convexo, plano, cóncavo ¿? (desarrollo del futuro).
En vez de cuestionar lo que hacen es confirmar. La materia es inagotable. Cuantos procesos estarán
desarrollándose. Eternidad de la materia en eterno movimiento (comprender con el menor
problema posible). Hoy en día se concibe a la materia como una interrupción de la nada. ¿Y qué
es la nada? Separa espacio de materia. Joudan. Una nada es un espacio, y un espacio es una
modalidad de la materia.

**La cosmogonía:** se descubre que hay unas estrellas que se desplazan a grandes velocidades: la
llamada expansión del universo, llegan a la concentración puntual del universo. Esto, dicen,
demuestra que ha habido un comienzo por tanto no es eterno, 2o tiene un límite. Dicen que antes
no existía el universo, momento inicial de la creación. Esto viene de que el entorno que conocemos
tiene 15.000.000.000 de años. Otros llegan a decir que tiene 6.000 millones de años, los hechos
demuestran que de la parte que conocemos ha empezado en esas fechas más o menos. Lo que se
está haciendo es generalizar lo poco que conocemos. Lo que se afirma de una parte no se puede
afirmar del todo. Se pretende (Russell) introducir por la puerta falsa la
divinidad.

El movimiento tiene una faceta cuantitativa y otra cualitativa.

La filosofía burguesa entra en un proceso de clara decadencia. Lukacs plantea que la contradicción
no es materialismo-idealismo, sino irracionalismo-racionalismo. Que plantea una aguda crisis de
la filosofía burguesa.

Bergson: desarrolla una metafísica llena de lacrimogenia.

Nietzsche: teoría del superhombre, una extraordinaria pluma. Las teorías que buscan una
salida al imperialismo. Teoría moral basada en los mejores y su dominio. Hombres privilegiados
y mentes borreguiles, apunta contra el cristianismo, intentando restablecer la moral de los
señores. El cristianismo confunde la bondad con la virtud. Son cristianos los más poderosos, los
más fuertes. Esto es puro racismo.

En los años 20 trata de reimpulsarse. Neopositivistas: surge en los círculos de Viena: el
positivismo, respuesta reaccionaria de la burguesía Comt. Plantea la necesidad de creer en la
ciencia positiva, niega la existencia de leyes en la realidad y plantea que la realidad son cosas que
nosotros elaboramos, el conocimiento. La nueva ciencia es una religiosidad, el mejor mundo es el
burgués y el problema es orden y progreso.

Neopositivistas: parte de los fenómenos, lleva a un cientificismo. Es el sujeto el que elabora un
sistema de ciencia, derecho, cae en un desarrollo de la lógica.
Elaborar sistemas derivados de la ciencia, matematicismo.

**Pitágoras:** planteó que la esencia de las cosas era el número, que todo podía ser medido, Platón lo
desarrolla. Todo el conocimiento lo reducen a fórmulas. Lo malo esta en sustituir la realidad por
las fórmulas, el hecho es que la matemática sale de la realidad material, el círculo salió de la rueda;
considera la matemática para sustituir la realidad. (hacer un agujero en la pared con una integral y
no con lo que representa la integral – un taladro- )-comentario.
La lógica: comienzan a analizar, plantean que el lenguaje es insuficiente y que hay que sustituirlo
por símbolos, para llegar a algo hay que simplificar todo. Es positivo en el sentido que nos da un
desarrollo de la lógica, como lógica simbólica. Hablan de criterios de
verificación, prueba de verdad. Se termina no analizando la materia, sino los análisis sobre la
materia (análisis lógico).

**Wittgenstein.** El más consecuente de los neopositivistas. “yo no puedo hablar del mundo, se me
puede preguntar de cómo yo interpreto el mundo, el mundo no es cognoscible, lo que se puede
hablar es del conocimiento que se tiene del mundo, no puedo hablar de los otros
sistemas porque no los conozco, lo mejor que puede hacerse es callarse, no se puede decir nada
sobre nada. Se llega a lo inefable. Silencio. Divinidad, se ha llegado al límite de contemplar”. Dios
a la vista. Científicos y análisis de la ciencia, logicismo. Negación absoluta del\ conocimiento.
Russell, Bertrand. Cameades en la antigüedad, Nunme y Rosses, sus análisis llevan a deshacer el
conocimiento.

Todos llegan al agnosticismo. Principia matemática. Creadores de la lógica moderna.
Matematicismo platónico, logicista, planomisticismo platónico “Todo lo que he dicho hasta ahora
no vale y lo que estoy diciendo ahora no sé si valdrá”.

Análisis, se quedan en el desmontaje y no llegan a montarlo, no hacen la síntesis. Sin embargo van
descubriendo paradojas que permiten avanzar, cuando pensamos estamos pensando en términos
finitos y han ido limpiando la filosofía y la ciencia. El conocimiento ha entrado a un momento
crítico, se produce un momento de síntesis, y nuevamente empezaron a expandirse. Demolición
de los conceptos de la ciencia, todo ha entrado en crisis. El proletariado va a
establecer esos nuevos principios. No ha acabado el proceso de demolición. Hay una clase que está
muriendo y sus principios mueren con ella. El desconcierto es una decantación.

**Existencialismo:** Heidegger. 1920. Análisis de la existencia, el creador Dios. La filosofía se debe
centrar en la existencia de las cosas. El hombre es la expresión de la existencia, viene de la nada y
marcha a la nada. No sabe nada de su existencia, de donde viene. En este tránsito se angustia,
cuando esto ocurre caben dos actitudes: enfrentar o huir de esa angustia. El
problema es enfrentar su angustia, enfrentar su muerte, ser para la muerte, esa es la identidad del
hombre, vivir para la muerte. Sirvió al nazismo, es expresión de una clase que está
agonizando. Expresión de la decadencia filosófica.

**Sartre:** es de la misma escuela. El hombre es un ser sin existencia y busca la existencia y busca
aferrarse a algo para expresar su existencia, el hombre reduce todo a la nada, busca aferrarse
a las cosas, pero eso es una salida en falso, en otro ser humano, el uno al otro se convierte en nada
(Auhilar). Otra salida es el amor, pero es la misma situación, entonces queda dios, pero dios no
existe. Entonces queda su propia libertad, esta es la solución. Solo le queda la
alternativa de vivir o morir. Pesimismo, sin salida la libertad es una correlación que se da en la
sociedad.

**Marcel:** el hombre viene de dios y va a dios, el problema entonces es llegar a dios.
Todas son expresiones de la clase que ya no tiene salida.
Neotomismo: Maritain. La iglesia se mantiene en el tomismo. Los pensadores católicos han
pensado ajustar el tomismo teniendo en cuenta el desarrollo de la ciencia en la filosofía. El hecho
de querer tomar una concepción feudal muestra la pobreza ideológica que tiene la iglesia. Nace
muerto pues es una filosofía que ya está muerta. Sucesores Husserl: aplicación de Deconte.
Fenomenología. Trata de superar los errores de Deconte. García Baca. García Morente, de la
escuela del neotomismo. Presidente Mao decía que uno no puede vacunarse contra el idealismo si
no se le conoce.

**Marxismo:** la ley principal: Plejanov planteaba que el Marxismo planteaba el monismo. El
materialismo es la base, la directriz es la dialéctica y de ésta lo principal es la contradicción. Marx
–Engels no llegan a plantear cual es lo medular. Con el C. Stalin se produce una regresión.
El Presidente Mao plantea que la única ley es la contradicción y las otras son derivaciones. Con el
Presidente Mao se llega al monismo filosófico; la única ley. Esto no implica que el sistema se haya
concluido. Cuestiones referentes a la libertad, por un lado es conciencia de la necesidad y el otro
aspecto es transformación de la necesidad y este es el principal. Dialéctica: las leyes más generales
del desarrollo del mundo natural, del mundo social y del conocimiento, entendiendo por tal el
reflejo de la realidad material en la mente del hombre. La dificultad estaría en las leyes. Es el
Presidente Mao el que plantea una única ley, considerando la ley de la contradicción como ley
única .

**El individualismo.** Plejanov: plantea el monismo, si bien parte de las leyes y las clases también
tiene en cuenta el individuo pues puede perturbarla. Asumir la ley y llevarla adelante, de la forma
más pura y cumplir el papel que la revolución demanda. Hay particularidades pero lo principal es
que asumen la ley y la llevan adelante. Marxismo-Leninismo-Maoísmo combatir el individualismo
y su raíz el egoísmo, combatir el yo por delante. El individuo históricamente se
va desenvolviendo, la propiedad privada potenció la individualidad y el egoísmo, la burguesía
potencia al máximo el individualismo hasta el exceso. El marxismo centrando en la clase rechaza
el individualismo, el egoísmo, en el P. es donde nos imprime una nueva forma de ser, nos va
modelando. La acción misma en la lucha de clases es la principal, el trabajar colectivamente nos
va diluyendo la formación que traemos.

Al hacer la revolución se transforma el mundo y también a los hombres. La raíz es el egoísmo y
es una base del revisionismo y requiere tiempo. Desarraigar el individualismo va a ser un
proceso largo. Al ir generando nuevas relaciones de producción más desarrolladas va a reflejarse
más y más en la idea en toda la sociedad.

Los comunistas debemos ser trompetas que anuncien el futuro. La ideología permite que
desarrollemos y avancemos en la lucha contra el egoísmo. Debemos ser los más avanzados.
Trabajamos por una meta que no vamos a ver. Reducir cada vez más el individualismo y el
egoísmo. Es en las luchas donde la acción golpea más el individualismo. La ideología es lo que
permite avanzar.

Lima, marzo-abril 1987