---
title: Editar
subtitle: Editar
shorttitle: "Editar"
description: |
  Accede al [PDF](https://achalmaedison.netlify.app/i3wm/2020-02-18-personalizando-i3wm/index.pdf) completo aquí.
abstract: |
  | Descubre cómo crear tu propio sitio web estático con Blogdown, una herramienta poderosa que combina R Markdown y Hugo. Aprende a usar comandos sencillos para personalizar, construir y alojar tu sitio web de manera fácil y rápida. ¡Comienza tu proyecto web hoy mismo!
keywords: [keyword1, keyword2]
categories:
  - Iwm
  - Blogdown
  - Desarrollo Web
  - Herramientas para R
tags:
  - RStudio
  - Blogdown
  - Comandos
  - DesarrolloWeb
citation:
  pdf-url: https://achalmaedison.netlify.app/i3wm/2020-02-18-personalizando-i3wm/index.pdf
date: "02/18/2020"
draft: true  # Modo de borrador (false = final, true = borrador)
---


1. Introducción a la personalización en i3wm
## Importancia de la personalización en un entorno de trabajo
## Ventajas de personalizar i3wm según tus preferencias

2. Configuración básica de i3wm
## Localización y estructura del archivo de configuración
## Ajustes iniciales recomendados
## Modificación de atajos de teclado y comandos

3. Temas visuales en i3wm
## Utilización de gestores de temas (theme managers)
## Cambio de colores y apariencia de la barra de estado
## Personalización de los bordes y estilos de las ventanas

4. Fondos de pantalla y lock screens
## Establecimiento de fondos de pantalla en i3wm
## Configuración de lock screens para mayor seguridad y personalización

5. Barra de estado personalizada
## Selección de barra de estado (status bar) adecuada para tus necesidades
## Configuración de información y widgets en la barra de estado
## Uso de programas externos para mostrar datos adicionales

6. Personalización avanzada con scripts y programas externos
## Automatización de tareas con scripts personalizados
## Integración de programas externos para funciones específicas

7. Gestión de ventanas mejorada
## Uso de aplicaciones externas para añadir funcionalidades
## Configuración de reglas específicas para ventanas

8. Compartir y descubrir configuraciones personalizadas
## Recursos en línea para encontrar y compartir configuraciones de i3wm
## Consideraciones al importar configuraciones de otros usuarios

9. Recursos adicionales y consejos útiles
## Herramientas y programas recomendados para la personalización en i3wm
## Comunidades y foros en línea para obtener soporte y compartir ideas


{{< include ../../_contenido-inicio.qmd >}}

{{< include ../_contenido_i3wm.qmd >}}

{{< include ../../_contenido-final.qmd >}}

