---
title: Editar
subtitle: Editar
shorttitle: "Editar"
description: |
  Accede al [PDF](https://achalmaedison.netlify.app/blog/posts/2021-07-14-comandos-blogdown/index.pdf) completo aquí.
abstract: |
  | Descubre cómo crear tu propio sitio web estático con Blogdown, una herramienta poderosa que combina R Markdown y Hugo. Aprende a usar comandos sencillos para personalizar, construir y alojar tu sitio web de manera fácil y rápida. ¡Comienza tu proyecto web hoy mismo!
keywords: [keyword1, keyword2]
categories:
  - Iwm
  - Blogdown
  - Desarrollo Web
  - Herramientas para R
tags:
  - RStudio
  - Blogdown
  - Comandos
  - DesarrolloWeb
citation:
  pdf-url: https://achalmaedison.netlify.app/blog/posts/2021-07-14-comandos-blogdown/index.pdf
date: "02/17/2020"
draft: true  # Modo de borrador (false = final, true = borrador)
---



1. Introducción al flujo de trabajo en i3wm
## Filosofía y enfoque de i3wm en la productividad
## Ventajas de utilizar atajos de teclado y comandos

1. Fundamentos de los atajos de teclado en i3wm
## Modificador principal y combinaciones de teclas
## Comandos básicos para el manejo de ventanas
## Atajos para la navegación entre workspaces

1. Dominando la gestión de ventanas
## Abrir, cerrar y mover ventanas
   3.2. Cambiar el tamaño y la posición de las ventanas
   3.3. Alternar entre modos de pantalla completa y en mosaico

1. Workspaces y organización del flujo de trabajo
## Creación y navegación entre workspaces
## Mover ventanas entre workspaces
## Establecer aplicaciones predeterminadas para workspaces específicos

1. Comandos avanzados y personalización de atajos
## Configurar atajos personalizados en el archivo de configuración
## Uso de scripts y programas externos en los atajos
## Atajos útiles para aplicaciones y utilidades comunes

1. Optimización del flujo de trabajo con comandos adicionales
## Utilizando comandos de i3wm para automatizar tareas
## Comandos de interacción con la barra de estado y otros componentes

1. Recursos adicionales y consejos
## Referencia rápida de atajos y comandos esenciales
## Prácticas recomendadas para optimizar el flujo de trabajo en i3wm
## Fuentes de información y ayuda para mejorar tus habilidades en i3wm


{{< include ../../_contenido-inicio.qmd >}}

{{< include ../_contenido_i3wm.qmd >}}

{{< include ../../_contenido-final.qmd >}}
