---
title: Rendimiento académico y genero de los ingresantes 2010 a la UNSCH
subtitle: Influencia del género en el rendimiento académico de los ingresantes 2010 a la Universidad Nacional de San Cristóbal de Huamanga
description: |
  Este blog analiza la influencia del género en el rendimiento académico de los estudiantes que ingresaron en 2010 a la Universidad Nacional de San Cristóbal de Huamanga. Se exploran las diferencias entre hombres y mujeres en relación con el rendimiento académico y se utiliza una metodología basada en datos proporcionados por la universidad. El estudio concluye que el rendimiento estimado para las mujeres es consistentemente superior al de los hombres.
categories:
  - Estadística para Economistas
tags:
  - Estadística para Economistas
  - Género y educación
  - Rendimiento académico
  - Universidad Nacional de San Cristóbal de Huamanga
  - Diferencias de género
  - Influencia del género en la educación
citation:
  author:
    - Edison Achalma
    - Geancarlos Alcarraz
    - Juan Alfaro
    - Luis De La Cruz 
    - David Pérez
  pdf-url: https://achalmaedison.netlify.app/docs/blog/posts/2019-12-30-rendimiento-academico-genero-ingresantes-2010/index.pdf
date: "12/30/2019"
---

**Influencia del género en el rendimiento académico de los ingresantes 2010 a la Universidad Nacional de San Cristóbal de Huamanga**

**Introducción:** El presente estudio se enfoca en analizar la relación entre el rendimiento académico y el género de los estudiantes que ingresaron en el año 2010 a la Universidad Nacional de San Cristóbal de Huamanga. Se consideran variables endógenas el rendimiento académico y variables exógenas el género de los estudiantes.

El rendimiento académico se define como el resultado del esfuerzo y la capacidad de trabajo del estudiante. Se ha seleccionado esta variable debido a la existencia de diferencias significativas entre hombres y mujeres en cuanto a las relaciones entre variables reticulares y rendimiento académico (Requena Fèlix, 1998, p. 241).

El género se analiza para determinar cómo ciertas condiciones relacionadas con el mismo influyen en mayor o menor medida en los resultados obtenidos en el rendimiento académico.

**Metodología:** Para la realización de este trabajo, se consultaron los artículos contenidos en el archivo Marco referencial-Trabajos de investigación proporcionados por el profesor encargado del curso de Estadística para Economistas II. Uno de los artículos consultados es "Género, redes de amistad y rendimiento académico" de Félix Requena Santos (1998), publicado por la Universidad de Santiago de Compostela, Departamento de Sociología, España.

Los datos utilizados en este estudio fueron obtenidos de la base de datos proporcionada por el Centro de Información y Sistemas de la Universidad Nacional de San Cristóbal de Huamanga. Estas bases de datos contienen información sobre los alumnos ingresantes en 2010 y su trayectoria académica dentro de la universidad.

**Conclusiones:** Uno de los hallazgos destacables es que el rendimiento estimado para las mujeres es consistentemente superior al de los hombres. De la promoción del año 2010, se encontraron 502 alumnos, de los cuales el 59% (296) son varones y el 41% (206) son mujeres.

Dado que los datos disponibles presentan limitaciones, en este estudio se investigará únicamente la variable exógena del género, la cual tiene un gran impacto en el rendimiento académico.

**Agradecimientos:** Queremos expresar nuestro más sincero agradecimiento al Centro de Información y Sistemas de la Universidad Nacional de San Cristóbal de Huamanga por proporcionarnos los datos necesarios para llevar a cabo este trabajo.
